(function(){
'use strict';
const $=id=>document.getElementById(id),entry=$('myEventAdsEntry'),panel=$('myEventAdsPanel'),admin=$('myEventAdminAds');if(!entry||!panel||!admin)return;
let isTest=false,feedRows=[],spacing=6,consent=false,observer,timers=new Map(),feedBusy=false,epoch=0,currentUid=null;
const money=v=>v==null?'Tarif à configurer':(v/100).toLocaleString('fr-FR',{style:'currency',currency:'EUR'});
const node=(tag,text,cls)=>{const e=document.createElement(tag);if(text!=null)e.textContent=String(text);if(cls)e.className=cls;return e;};
const status=(target,text)=>{target.textContent=text;};
async function session(){if(typeof sb==='undefined')throw Error('Connexion requise.');const r=await sb.auth.getSession();if(r.error||!r.data?.session)throw Error('Connexion requise.');return r.data.session;}
async function request(action,payload={}){
 if(!isTest)throw Error('Régie disponible uniquement en TEST.');const s=await session(),uid=s.user.id;
 const r=await fetch('/api/create-payment-session',{method:'POST',headers:{Authorization:'Bearer '+s.access_token,'Content-Type':'application/json'},body:JSON.stringify({action:'ads_'+action,payload}),cache:'no-store',signal:AbortSignal.timeout(30000)});const data=await r.json();const latest=await session();if(latest.user.id!==uid)throw Error('Compte changé.');if(!r.ok)throw Error(data.error||'Régie indisponible.');return data;
}
function button(text,fn){const b=node('button',text);b.type='button';b.onclick=async()=>{b.disabled=true;try{await fn();}catch(e){status($('myEventAdsMessage'),e.message);}finally{b.disabled=false;}};return b;}
function campaigns(rows,target,manage=false){target.replaceChildren();if(!rows.length)target.append(node('p','Aucune campagne.'));for(const c of rows){const card=node('article',null,'adCampaign');card.append(node('h4',c.title),node('p',c.business+' · '+c.status),node('p',c.body),node('p','Impressions : '+c.impressions+' · Clics : '+c.clicks+' · Dépenses versées : '+money(c.paid_at?c.price_cents:0)),node('small',c.review_reason||'Validation administrative obligatoire.'));const actions=node('div',null,'adActions');if(manage){for(const [label,state] of [['Valider','approved'],['Refuser','rejected'],['Suspendre','suspended']]){const b=button(label,async()=>{const reason=prompt('Motif de la décision (visible par le professionnel)');if(reason===null)return;await request('review',{id:c.id,status:state,reason});await loadAdmin();});b.disabled=state==='approved'&&!['pending','suspended'].includes(c.status)||state==='rejected'&&(c.status!=='pending'||!!c.paid_at)||state==='suspended'&&c.status==='suspended';actions.append(b);}}else if(c.status==='approved'&&!c.paid_at&&c.price_cents!=null){actions.append(button('Payer avec Stripe TEST',async()=>{const data=await request('checkout',{id:c.id});if(data.test!==true||!/^https:\/\/checkout\.stripe\.com\//.test(data.url))throw Error('Paiement non autorisé.');location.assign(data.url);}));}card.append(actions);target.append(card);}}
async function catalog(){const data=await request('catalog');spacing=data.settings.spacing;const plans=$('myEventAdsPlans'),select=$('myEventAdsPlan');plans.replaceChildren();select.replaceChildren();for(const p of data.plans){const card=node('article',null,'adPlan');card.append(node('h4',p.name),node('strong',money(p.price_cents)),node('small',p.duration_days?p.duration_days+' jours':'Durée à configurer'));plans.append(card);select.append(new Option(p.name+' · '+money(p.price_cents),p.key));}return data;}
async function open(){panel.hidden=false;status($('myEventAdsMessage'),'Chargement…');try{await catalog();campaigns(await request('mine'),$('myEventAdsCampaigns'));status($('myEventAdsMessage'),'TEST uniquement · aucun paiement réel.');}catch(e){status($('myEventAdsMessage'),e.message);}}
entry.onclick=open;$('myEventAdsClose').onclick=()=>{panel.hidden=true;entry.focus();};
$('myEventAdsForm').onsubmit=async e=>{e.preventDefault();const form=e.currentTarget,b=form.querySelector('button[type="submit"]');b.disabled=true;try{const payload=Object.fromEntries(new FormData(form));if(payload.professional!=='on')throw Error('Confirmez votre activité professionnelle.');await request('create',payload);form.reset();await open();status($('myEventAdsMessage'),'Campagne soumise à validation. Aucun paiement effectué.');}catch(err){status($('myEventAdsMessage'),err.message);}finally{b.disabled=false;}};
async function loadAdmin(){
 const seq=epoch;admin.replaceChildren(node('p','Chargement des campagnes…'));
 try{const data=await request('admin_list'),cat=await request('catalog');if(seq!==epoch)return;admin.replaceChildren();admin.append(node('p','Revenus directs encaissés (TEST) : '+money(data.revenue_cents)),node('p','Google AdSense non connecté. AdMob : future application native. Aucun revenu externe synchronisé.'));
 const settings=node('form');settings.innerHTML='<h4>Emplacement dans le fil</h4><label>Publicités directes TEST actives <input type="checkbox" name="enabled"></label><label>Une publicité après combien de publications ? <input type="number" name="spacing" min="5" max="30" required></label><button>Enregistrer</button>';
 settings.elements.enabled.checked=cat.settings.enabled;settings.elements.spacing.value=cat.settings.spacing;settings.onsubmit=async e=>{e.preventDefault();await adminAction(()=>request('settings',{enabled:settings.elements.enabled.checked,spacing:Number(settings.elements.spacing.value)}));};admin.append(settings);
 const prices=node('div',null,'adPlans');for(const p of cat.plans){const form=node('form',null,'adPlan');form.innerHTML='<h4></h4><label>Prix du forfait (€) <input type="number" name="price" min="0.50" max="100000" step="0.01" required></label><label>Durée (jours) <input type="number" name="duration" min="1" max="365" required></label><button>Enregistrer le tarif</button>';form.querySelector('h4').textContent=p.name;form.elements.price.value=p.price_cents==null?'':p.price_cents/100;form.elements.duration.value=p.duration_days||'';form.onsubmit=async e=>{e.preventDefault();await adminAction(()=>request('plan',{key:p.key,price_cents:Math.round(Number(form.elements.price.value)*100),duration_days:Number(form.elements.duration.value)}));};prices.append(form);}admin.append(prices);
 const list=node('div');campaigns(data.campaigns,list,true);admin.append(list);
 const external=node('form');external.innerHTML='<h4>Revenus externes déclarés manuellement</h4><label>Régie <select name="provider"><option>AdSense</option><option>AdMob</option></select></label><label>Mois <input type="month" name="month" required></label><label>Revenu déclaré (€) <input type="number" name="amount" min="0" step="0.01" required></label><button>Enregistrer la déclaration</button>';external.onsubmit=async e=>{e.preventDefault();await adminAction(()=>request('external_revenue',{provider:external.elements.provider.value,month:external.elements.month.value+'-01',amount_cents:Math.round(Number(external.elements.amount.value)*100)}));};admin.append(external);for(const row of data.external)admin.append(node('p',row.provider+' · '+row.month+' · '+money(row.amount_cents)+' · saisie manuelle'));
 }catch(e){if(seq===epoch)admin.replaceChildren(node('p',e.message,'adStatus'));}
}
async function adminAction(fn){const buttons=[...admin.querySelectorAll('button')];buttons.forEach(b=>b.disabled=true);try{await fn();await loadAdmin();await loadFeed();}catch(e){admin.prepend(node('p',e.message,'adStatus'));}finally{buttons.filter(b=>b.isConnected).forEach(b=>b.disabled=false);}}
function clearTracking(){observer?.disconnect();for(const timer of timers.values())clearTimeout(timer);timers.clear();}
function track(card,kind){if(!consent||document.visibilityState!=='visible'||!card.dataset.metricToken)return;request('metric',{token:card.dataset.metricToken,kind,consent:true}).catch(()=>{});}
function arm(){clearTracking();if(!consent||!('IntersectionObserver' in window))return;observer=new IntersectionObserver(entries=>{for(const e of entries){clearTimeout(timers.get(e.target));timers.delete(e.target);if(e.isIntersecting&&e.intersectionRatio>=.5)timers.set(e.target,setTimeout(()=>{track(e.target,'impression');observer.unobserve(e.target);timers.delete(e.target);},1000));}},{threshold:[.5]});document.querySelectorAll('.adSponsored').forEach(c=>observer.observe(c));}
function renderFeed(){const feed=$('socialFeed');if(!feed)return;clearTracking();feed.querySelectorAll('.adSponsored').forEach(e=>e.remove());const posts=[...feed.children].filter(e=>e.classList.contains('socialPost'));feedRows.forEach((row,i)=>{const anchor=posts[spacing*(i+1)-1];if(!anchor)return;const card=node('article',null,'adSponsored');card.dataset.metricToken=row.metric_token||'';card.append(node('small','Sponsorisé · '+row.business),node('h3',row.title),node('p',row.body));const link=node('a','En savoir plus');link.href=row.target_url;link.target='_blank';link.rel='noopener noreferrer';link.onclick=()=>track(card,'click');card.append(link);anchor.after(card);});arm();}
async function loadFeed(){if(!isTest||feedBusy)return;feedBusy=true;const seq=epoch;try{const cat=await request('catalog'),rows=await request('feed');if(seq!==epoch)return;spacing=cat.settings.spacing;feedRows=rows;renderFeed();}catch{if(seq===epoch){feedRows=[];renderFeed();}}finally{feedBusy=false;if(seq!==epoch&&currentUid)setTimeout(loadFeed,0);}}
$('myEventAdsConsent').onchange=e=>{consent=e.target.checked;arm();};document.addEventListener('visibilitychange',()=>{if(document.visibilityState!=='visible')clearTracking();else arm();});
const feed=$('socialFeed');if(feed)new MutationObserver(ms=>{if(ms.some(m=>[...m.addedNodes,...m.removedNodes].some(n=>n.nodeType===1&&n.classList.contains('socialPost'))))renderFeed();}).observe(feed,{childList:true});
window.myeventAds=Object.freeze({loadAdmin});
window.myeventRuntime?.ready.then(async c=>{isTest=c.isTest===true&&c.environment==='preview'&&c.projectRef==='ahyyknfjsielnqyoxqgh';entry.hidden=!isTest;$('myEventAdminAdsTab').hidden=!isTest;$('myEventAdsPrivacy').hidden=!isTest;if(!isTest)return;try{const s=await session();currentUid=s.user.id;}catch{}loadFeed();if(typeof sb!=='undefined')sb.auth.onAuthStateChange((_event,s)=>{if(s?.user.id===currentUid)return;currentUid=s?.user.id||null;epoch++;feedRows=[];consent=false;$('myEventAdsConsent').checked=false;panel.hidden=true;$('myEventAdsForm').reset();$('myEventAdsCampaigns').replaceChildren();admin.replaceChildren();renderFeed();if(s)setTimeout(loadFeed,0);});}).catch(()=>{});
})();
