(function(){
 function setup(){
  const host=document.getElementById('m58AccommodationSearchBox');if(!host||host.querySelector('.sabreSearch'))return;
  const section=document.createElement('section');section.className='sabreSearch';
  section.innerHTML='<h3>Hôtels · recherche Sabre CERT</h3><p>Recherche de test. Les réservations restent chez nos partenaires.</p><form class="hotelSearchForm"><label>Destination<input name="destination" required maxlength="200" placeholder="Paris"></label><div class="row"><label>Arrivée<input name="checkIn" type="date" required></label><label>Départ<input name="checkOut" type="date" required></label></div><div class="row"><label>Adultes<input name="guests" type="number" value="2" min="1" max="30" required></label><label>Chambres<input name="rooms" type="number" value="1" min="1" max="30" required></label></div><button type="submit">Rechercher des hôtels</button></form><p role="status" class="hotelSearchStatus"></p><details class="hotelSearchDiagnostics" hidden><summary>Diagnostic de recherche CERT</summary><pre></pre></details><div class="hotelSearchResults"></div><button type="button" class="hotelSearchMore" hidden>Afficher plus d’hôtels</button>';
  host.prepend(section);const form=section.querySelector('form'),status=section.querySelector('[role=status]'),results=section.querySelector('.hotelSearchResults');
  if(typeof event==='object'&&event?.location){form.elements.destination.value=event.location;form.elements.checkIn.value=String(event.event_date||'').slice(0,10);}
  const more=section.querySelector('.hotelSearchMore');let nextOffset=null,lastQuery=null;const seen=new Set();
  more.onclick=()=>search(null,true);
  async function search(e,append=false){e?.preventDefault();const button=form.querySelector('button');if(button.disabled)return;button.disabled=true;more.disabled=true;if(!append){results.replaceChildren();seen.clear();more.hidden=true;}status.textContent='Recherche…';
   try{const q=append?{...lastQuery,offset:nextOffset}:Object.fromEntries(new FormData(form));q.guests=Number(q.guests);q.rooms=Number(q.rooms);q.type='hotel';if(!append)lastQuery={...q};const response=await fetch('/api/search-accommodation',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(q),signal:AbortSignal.timeout(30000)});const data=await response.json();if(!response.ok)throw Error(data.error||'Hôtels indisponibles.');status.textContent=(data.warnings||[]).join(' ')+' · '+(data.results||[]).length+' hôtel(s) sur cette page.'+(data.supplierCount>(data.results||[]).length?' '+data.supplierCount+' entrées fournisseur reçues ; doublons ou métadonnées incomplètes écartés.':'')+(data.status==='unavailable'?' Recherche indisponible.':(data.results||[]).length===0?' Aucun hôtel retourné pour ces critères.':'');const diagnostic=section.querySelector('.hotelSearchDiagnostics');diagnostic.hidden=!data.diagnostics;diagnostic.querySelector('pre').textContent=data.diagnostics?JSON.stringify(data.diagnostics,null,2):'';nextOffset=data.nextOffset||null;more.hidden=!nextOffset;
    for(const hotel of data.results||[]){if(seen.has(hotel.id))continue;seen.add(hotel.id);const card=document.createElement('article');card.className='placeCard';card.innerHTML=window.MyEventPlaceCard.content(hotel);const info=document.createElement('p');info.textContent=(hotel.availability||'')+(hotel.price!=null?' · Tarif pour le séjour · taxes '+(hotel.taxInclusive?'incluses':'à vérifier')+' · frais '+(hotel.feesInclusive?'inclus':'à vérifier'):'');card.append(info);for(const item of hotel.conditions||[]){const p=document.createElement('p');p.textContent=(item.refundable===true?'Remboursable selon conditions':item.refundable===false?'Non remboursable':'Remboursement non précisé')+(item.text?' · '+item.text:'');card.append(p);}if(hotel.equipment?.length){const p=document.createElement('p');p.textContent=hotel.equipment.join(' · ');card.append(p);}results.append(card);}
   }catch(error){status.textContent=error.name==='TimeoutError'?'Recherche trop longue. Réessaie.':error.message;}finally{button.disabled=false;more.disabled=false;}
  }
  form.onsubmit=e=>search(e);
 }
 if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',setup,{once:true});else setup();
})();
