import test from 'node:test';import assert from 'node:assert/strict';import {createRequire} from 'node:module';const require=createRequire(import.meta.url);const {validate}=require('../js/accommodation-search-contract');const handler=require('../server/search-accommodation');const {createAccommodationService}=require('../lib/accommodation-provider');
const q={destination:'Paris',checkIn:'2099-01-02',checkOut:'2099-01-03',guests:2,rooms:1,type:'all'};
test('valid search and invalid dates/counts',()=>{assert.equal(validate(q),'');for(const change of [{destination:''},{checkIn:'2099-02-31'},{checkIn:'2000-01-01'},{checkOut:q.checkIn},{guests:0},{guests:1.5},{guests:31},{rooms:3},{rooms:0},{type:'unknown'}])assert.ok(validate({...q,...change}));});
async function request(method,body){let status=200,data;const headers={};await handler({method,body},{setHeader(k,v){headers[k]=v;},status(v){status=v;return this;},json(v){data=v;return this;}});return {status,data,headers};}
test('no authorized supplier means no offers, prices or links',async()=>{const r=await request('POST',q);assert.equal(r.status,200);assert.equal(r.data.status,'unavailable');assert.deepEqual(r.data.results,[]);assert.equal(r.headers['Cache-Control'],'no-store');});
test('endpoint rejects invalid inputs and GET',async()=>{assert.equal((await request('GET',q)).status,405);assert.equal((await request('POST',{...q,guests:0})).status,400);});
test('supplier can be replaced without changing query',async()=>{let received;const service=createAccommodationService({async search(query){received=query;return {status:'empty',results:[],warnings:[]};}});assert.equal((await service.search(q)).status,'empty');assert.equal(received,q);});
import vm from 'node:vm';import {readFileSync} from 'node:fs';
const runtime=readFileSync(new URL('../js/accommodation-search-runtime.js',import.meta.url),'utf8');
function ui(fetch){const nodes={};for(const [id,value] of Object.entries({Destination:'Paris',Checkin:q.checkIn,Checkout:q.checkOut,Guests:'2',Rooms:'1',Type:'all',SearchResult:'',SearchLaunch:''})){nodes['m58Accommodation'+id]={value,disabled:false,textContent:'',children:[],replaceChildren(){this.children=[];},append(...x){this.children.push(...x);},setAttribute(){}};}const context=vm.createContext({$:id=>nodes[id],MyEventAccommodation:{validate},fetch,AbortController,setTimeout,clearTimeout,URLSearchParams,document:{createElement:tag=>({tag})}});vm.runInContext(runtime,context);return {nodes,run:()=>context.v58SearchAccommodation()};}
test('UI shows unavailable status without fake offers and restores button',async()=>{const {nodes,run}=ui(async()=>({ok:true,json:async()=>({status:'unavailable',results:[]})}));await run();assert.match(nodes.m58AccommodationSearchResult.textContent,/Aucun prix ni disponibilité/);assert.equal(nodes.m58AccommodationSearchLaunch.disabled,false);assert.match(nodes.m58AccommodationSearchResult.children[1].href,/^https:\/\/www.google.com\/search\?/);});
test('network and non-JSON errors allow retry',async()=>{for(const fetch of [async()=>{throw Error('network');},async()=>({ok:false,json:async()=>{throw Error('HTML');}})]){const {nodes,run}=ui(fetch);await run();assert.match(nodes.m58AccommodationSearchResult.textContent,/Réessaie/);assert.equal(nodes.m58AccommodationSearchLaunch.disabled,false);assert.equal(nodes.m58AccommodationSearchResult.children.length,0);}});
test('invalid guest count never calls network',async()=>{const {nodes,run}=ui(()=>{throw Error('unexpected request');});nodes.m58AccommodationGuests.value='0';await run();assert.match(nodes.m58AccommodationSearchResult.textContent,/voyageurs/);});
