import {JSDOM} from 'jsdom';
import {readFile} from 'node:fs/promises';
import assert from 'node:assert/strict';
const html=await readFile(new URL('../index.html',import.meta.url),'utf8');
const admin=html.match(/<div style="padding:12px 16px"><button[^>]*id="myeventAdminEntry"[^>]*><\/button><\/div>/)?.[0]||'<button id="myeventAdminEntry" hidden></button>';
const section=html.match(/<section id="myeventAdminPanel"[\s\S]*?<\/section>/)?.[0];
assert.ok(section);
const dom=new JSDOM('<!doctype html><html><body>'+admin+section+'</body></html>',{runScripts:'outside-only',url:'https://preview.example.test/'});
const {window}=dom;window.scrollTo=()=>{};window.confirm=()=>true;window.prompt=()=> 'Motif détaillé';
window.HTMLElement.prototype.scrollIntoView=function(){};
const calls=[];
window.sb={auth:{getUser:async()=>({data:{user:{id:'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa'}}}),onAuthStateChange:()=>({data:{subscription:{unsubscribe(){}}}})},rpc:async(name,args)=>{
 calls.push({name,args});
 if(name==='myevent_is_admin')return{data:true};
 if(name==='myevent_admin_overview')return{data:{users:2,events:1,generated_at:new Date().toISOString()}};
 if(name==='myevent_admin_list')return{data:args.p_kind==='users'?[{id:'bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb',username:'userb',display_name:'Compte B',created_at:new Date().toISOString(),suspended:false,is_admin:false}]:[]};
 return{data:[]};
 }};
window.eval(await readFile(new URL('../js/admin-runtime.js',import.meta.url),'utf8'));
await new Promise(r=>setTimeout(r,500));
const entry=window.document.getElementById('myeventAdminEntry');assert.equal(entry.hidden,false);
entry.click();await new Promise(r=>setTimeout(r,30));
assert.equal(window.document.getElementById('myeventAdminPanel').hidden,false);
window.document.querySelector('[data-admin-tab=users]').click();await new Promise(r=>setTimeout(r,30));
assert.equal(window.document.querySelectorAll('#myeventAdminUsers .adminCard').length,1);
assert.equal(window.document.querySelector('[data-admin-tab=users]').getAttribute('aria-current'),'page');
window.document.querySelector('#myeventAdminUsers .adminDanger').click();await new Promise(r=>setTimeout(r,30));
assert.ok(calls.some(x=>x.name==='myevent_admin_action'&&x.args.p_action==='suspend'));
window.document.getElementById('myeventAdminClose').click();assert.equal(window.document.getElementById('myeventAdminPanel').hidden,true);
window.close();console.log('Admin V2 UI: mobile navigation, list, confirmation action and close OK');
