import {PGlite} from '@electric-sql/pglite';
import {readFile} from 'node:fs/promises';
import assert from 'node:assert/strict';
const db=new PGlite();
const A='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',B='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb',C='cccccccc-cccc-4ccc-8ccc-cccccccccccc',E='dddddddd-dddd-4ddd-8ddd-dddddddddddd',L='eeeeeeee-eeee-4eee-8eee-eeeeeeeeeeee';
async function as(id,sql,args=[]){return db.transaction(async tx=>{await tx.exec('set local role authenticated');await tx.query("select set_config('request.jwt.claim.sub',$1,true)",[id]);return tx.query(sql,args);});}
await db.exec(`create role authenticated;create role anon;create schema auth;
create table auth.users(id uuid primary key,created_at timestamptz default now(),banned_until timestamptz);
create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
grant usage on schema auth to authenticated;
create table public.profiles(id uuid primary key,display_name text,username text,avatar text);
create table public.events(id uuid primary key,creator_id uuid,name text,location text,event_date timestamptz,visibility text default 'public',created_at timestamptz default now());
create table public.marketplace_listings(id uuid primary key,owner_id uuid,title text,city text,status text,price_cents int,created_at timestamptz default now());
create function public.event_is_visible(p_event uuid,p_user uuid default auth.uid()) returns boolean language sql stable as $$select exists(select 1 from public.events where id=p_event and visibility='public')$$;
create function public.event_is_member(p_event uuid,p_user uuid default auth.uid()) returns boolean language sql stable as $$select exists(select 1 from public.events where id=p_event and creator_id=p_user)$$;
create function public.are_friends(uuid,uuid) returns boolean language sql stable as $$select false$$;
create function public.event_protect_identity() returns trigger language plpgsql as $$begin return new;end$$;
create trigger event_protect_identity_v2 before update on public.events for each row execute function public.event_protect_identity();
alter table public.events enable row level security;create policy events_read on public.events for select to authenticated using(true);
alter table public.marketplace_listings enable row level security;create policy listings_read on public.marketplace_listings for select to authenticated using(true);
create policy listings_write on public.marketplace_listings for update to authenticated using(owner_id=auth.uid()) with check(owner_id=auth.uid());
grant select on public.events,public.marketplace_listings,public.profiles to authenticated;
grant update(status) on public.marketplace_listings to authenticated;`);
for(const id of [A,B,C])await db.query('insert into auth.users(id) values($1)',[id]);
await db.query('insert into public.profiles values($1,$2,$3,null)',[A,'Admin','admin']);
await db.query('insert into public.profiles values($1,$2,$3,null)',[B,'Compte B','compte_b']);
await db.query('insert into public.events(id,creator_id,name) values($1,$2,$3)',[E,B,'Sortie']);
await db.query('insert into public.marketplace_listings values($1,$2,$3,$4,$5,$6,now())',[L,B,'Annonce','Gap','active',1200]);
for(const name of ['202610030001_platform_admin.sql','202610030002_admin_partner_content.sql','202610030003_admin_v2.sql']){
 const migration=await readFile(new URL('../supabase/migrations/'+name,import.meta.url),'utf8');
 await db.exec(migration);
}
await db.query("insert into public.platform_admins(user_id) values($1)",[A]);
assert.equal((await as(A,"select jsonb_array_length(public.myevent_admin_list('users')) n")).rows[0].n,3);
await assert.rejects(()=>as(B,"select public.myevent_admin_list('users')"));
await assert.rejects(()=>as(A,"select public.myevent_admin_action('user',$1,'suspend','','sufficient reason')",[A]));
await as(A,"select public.myevent_admin_action('user',$1,'suspend','','sufficient reason')",[B]);
assert.equal((await db.query('select banned_until>now() as banned from auth.users where id=$1',[B])).rows[0].banned,true);
assert.equal((await as(B,'select count(*)::int n from public.events')).rows[0].n,0);
await as(A,"select public.myevent_admin_action('event',$1,'hide','','sufficient reason')",[E]);
assert.equal((await as(C,'select public.event_is_visible($1) visible',[E])).rows[0].visible,false);
await as(A,"select public.myevent_admin_action('listing',$1,'hide','','sufficient reason')",[L]);
assert.equal((await as(C,'select count(*)::int n from public.marketplace_listings')).rows[0].n,0);
assert.equal((await as(B,"update public.marketplace_listings set status='active' where id=$1",[L])).affectedRows,0);
await as(A,"select public.myevent_admin_action('user',$1,'reactivate')",[B]);
assert.equal((await as(B,'select count(*)::int n from public.events')).rows[0].n,1);
await assert.rejects(()=>as(B,"update public.marketplace_listings set status='active' where id=$1",[L]));
await assert.rejects(()=>as(C,"select public.myevent_report('event',$1,'A serious report')",[E]));
await as(A,"select public.myevent_admin_action('event',$1,'restore')",[E]);
await as(C,"select public.myevent_report('event',$1,'A serious report')",[E]);
await assert.rejects(()=>as(C,"select public.myevent_report('event',$1,'A serious report')",[E]));
const report=(await db.query('select id from public.admin_reports where target_id=$1',[E])).rows[0];
await as(A,"select public.myevent_admin_action('report',$1,'resolve')",[report.id]);
assert.equal((await db.query('select status from public.admin_reports where id=$1',[report.id])).rows[0].status,'resolved');
await as(A,"select public.myevent_admin_partner_content_save('getyourguide','activity','Test activity')");
assert.ok((await db.query("select count(*)::int n from public.admin_audit_log where target_kind='partner_content'")).rows[0].n>0);
await as(A,"select public.myevent_admin_action('event',$1,'visibility','friends')",[E]);
assert.equal((await db.query('select visibility from public.events where id=$1',[E])).rows[0].visibility,'friends');
assert.ok((await as(A,"select jsonb_array_length(public.myevent_admin_list('audit')) n")).rows[0].n>=5);
await assert.rejects(()=>as(B,"select public.myevent_admin_config('module','games',false)"));
await as(A,"select public.myevent_admin_config('module','games',false)");
assert.equal((await db.query("select enabled from public.admin_app_settings where key='games'")).rows[0].enabled,false);
console.log('Admin V2: roles, suspension, moderation, reports, config and audit OK');
