import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';
const {PGlite}=await import(process.env.PGLITE_MODULE_URL||'@electric-sql/pglite');const db=new PGlite();
const owner='11111111-1111-4111-8111-111111111111',other='22222222-2222-4222-8222-222222222222',admin='33333333-3333-4333-8333-333333333333';let checks=0;
async function as(uid,fn,role='authenticated'){return db.transaction(async tx=>{await tx.exec('set local role '+role);await tx.query("select set_config('request.jwt.claim.sub',$1,true)",[uid||'']);return fn(tx);});}
async function rpc(uid,action,payload={}){return as(uid,async tx=>(await tx.query('select public.myevent_ads($1,$2::jsonb) result',[action,JSON.stringify(payload)])).rows[0].result);}
async function deny(fn){await assert.rejects(fn);checks++;}
try{await db.exec(`create role anon;create role authenticated;create role service_role;create schema auth;create table auth.users(id uuid primary key,banned_until timestamptz);create table public.admin_account_controls(user_id uuid primary key,suspended boolean);create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;create function public.myevent_account_active() returns boolean language sql stable security definer as $$select auth.uid() is not null and not exists(select 1 from auth.users where id=auth.uid() and banned_until>now()) and not exists(select 1 from public.admin_account_controls where user_id=auth.uid() and suspended)$$;grant usage on schema auth to authenticated,anon,service_role;create function public.myevent_is_admin() returns boolean language sql stable as $$select auth.uid()='${admin}'::uuid$$;`);await db.query('insert into auth.users(id) values($1),($2),($3)',[owner,other,admin]);await db.exec(await readFile(new URL('../supabase/migrations/202610100001_ads_v1_test.sql',import.meta.url),'utf8'));checks++;
await deny(()=>as('',tx=>tx.query("select public.myevent_ads('catalog','{}')"),'anon'));await deny(()=>rpc(null,'catalog'));await deny(()=>as(owner,tx=>tx.query('select * from public.ad_campaigns')));await deny(()=>as(owner,tx=>tx.query("insert into public.ad_campaigns(owner_id,title) values(auth.uid(),'bad')")));await deny(()=>rpc(owner,'plan',{key:'essential',price_cents:9900,duration_days:7}));await deny(()=>rpc(owner,'admin_list'));await deny(()=>rpc(owner,'external_revenue',{provider:'AdSense',month:'2026-10-01',amount_cents:100}));
const cat=await rpc(owner,'catalog');assert.equal(cat.plans.length,4);assert(cat.plans.every(p=>p.price_cents===null));assert.equal(cat.settings.enabled,false);checks++;
const payload={professional:'on',business:'Entreprise TEST',title:'Campagne TEST',body:'Contenu de campagne TEST.',target_url:'https://example.com/offre',plan_key:'essential',status:'approved',owner_id:other,price_cents:1,paid_at:new Date().toISOString()};const c=await rpc(owner,'create',payload);assert.equal(c.owner_id,owner);assert.equal(c.status,'pending');assert.equal(c.price_cents,null);assert.equal(c.paid_at,null);checks++;await deny(()=>rpc(other,'quote',{id:c.id}));await deny(()=>rpc(owner,'review',{id:c.id,status:'approved'}));await deny(()=>rpc(admin,'review',{id:c.id,status:'approved'}));
await deny(()=>rpc(owner,'create',{...payload,target_url:'javascript:alert(1)'}));await deny(()=>rpc(owner,'create',{...payload,target_url:'https://user:secret@example.com'}));
await rpc(admin,'plan',{key:'essential',price_cents:9900,duration_days:7});await rpc(admin,'review',{id:c.id,status:'approved'});const quote=await rpc(owner,'quote',{id:c.id});assert.equal(quote.price_cents,9900);checks++;
assert.deepEqual(await rpc(owner,'feed'),[]);await deny(()=>as(owner,tx=>tx.query("select public.myevent_ads_paid($1,'cs_test_1',9900,'eur')",[c.id])));await deny(()=>as(owner,tx=>tx.query("select public.myevent_ads_count($1,'click')",[c.id])));
const paid=(amount=9900,session='cs_test_1',currency='eur')=>as(null,tx=>tx.query('select public.myevent_ads_paid($1,$2,$3,$4)',[c.id,session,amount,currency]),'service_role');await deny(()=>paid(1));await deny(()=>paid(9900,'cs_live_1'));await deny(()=>paid(9900,'cs_test_1','usd'));await paid();await paid();checks++;await deny(()=>paid(9900,'cs_test_2'));
await rpc(admin,'settings',{enabled:true,spacing:6});assert.equal((await rpc(owner,'feed')).length,1);assert.equal((await rpc(other,'mine')).length,0);checks++;
await as(null,tx=>tx.query("select public.myevent_ads_count($1,'impression')",[c.id]),'service_role');await as(null,tx=>tx.query("select public.myevent_ads_count($1,'click')",[c.id]),'service_role');assert.equal((await rpc(owner,'mine'))[0].impressions,1);assert.equal((await rpc(owner,'mine'))[0].clicks,1);assert.equal((await rpc(admin,'admin_list')).revenue_cents,9900);checks++;
await rpc(admin,'review',{id:c.id,status:'suspended',reason:'Test de suspension'});assert.deepEqual(await rpc(owner,'feed'),[]);const counted=await as(null,tx=>tx.query("select public.myevent_ads_count($1,'click') result",[c.id]),'service_role');assert.equal(counted.rows[0].result,false);await rpc(admin,'review',{id:c.id,status:'approved'});checks++;
await rpc(admin,'external_revenue',{provider:'AdSense',month:'2026-10-01',amount_cents:100});await rpc(admin,'external_revenue',{provider:'AdSense',month:'2026-10-01',amount_cents:200});assert.equal((await rpc(admin,'admin_list')).external.length,1);checks++;
await deny(()=>rpc(admin,'settings',{spacing:1}));await deny(()=>rpc(admin,'plan',{key:'premium',price_cents:0,duration_days:1}));await deny(()=>rpc(admin,'plan',{key:'premium',price_cents:100,duration_days:0}));
await rpc(admin,'plan',{key:'essential',price_cents:15000,duration_days:30});assert.equal((await rpc(owner,'mine'))[0].price_cents,9900);checks++;
await db.query('insert into public.admin_account_controls values($1,true)',[owner]);await deny(()=>rpc(owner,'mine'));assert.deepEqual(await rpc(other,'feed'),[]);checks++;await db.query('delete from public.admin_account_controls where user_id=$1',[owner]);await deny(()=>rpc(owner,'unknown'));console.log(`PASS PostgreSQL isolated: ${checks} checks, RLS/roles/ownership/moderation/frozen prices/payment replay/counters/settings/external revenue; no remote database.`);
}finally{await db.close();}
