import test from 'node:test';import assert from 'node:assert/strict';import {createRequire} from 'node:module';
const {handler,paid}=createRequire(import.meta.url)('../server/ads-handler.js');
const config={VERCEL_ENV:'preview',SUPABASE_URL:'https://ahyyknfjsielnqyoxqgh.supabase.co',SUPABASE_PUBLISHABLE_KEY:'sb_publishable_fake',MYEVENT_TEST_SUPABASE_REF:'ahyyknfjsielnqyoxqgh',VERCEL_URL:'myevent-test-example.vercel.app',SUPABASE_SERVICE_ROLE_KEY:'sb_secret_fake',STRIPE_SECRET_KEY:'sk_test_fake'};
function setup(){for(const [k,v] of Object.entries(config))process.env[k]=v;}
function response(status,data){return{ok:status>=200&&status<300,status,json:async()=>data};}
function call(body,auth='Bearer dummy'){const res={headers:{},setHeader(k,v){this.headers[k]=v;},status(s){this.code=s;return this;},json(v){this.body=v;return this;}};return handler({method:'POST',headers:{authorization:auth},body},res).then(()=>res);}
const original=global.fetch;
test('TEST boundary rejects production before any network',async()=>{setup();process.env.VERCEL_ENV='production';let calls=0;global.fetch=async()=>{calls++;throw Error('must not call');};const r=await call({action:'ads_catalog'});assert.equal(r.code,403);assert.equal(calls,0);});
test('wrong TEST project, missing auth and rejected user fail closed',async()=>{setup();process.env.SUPABASE_URL='https://nxxvadbliinhvkirqkkl.supabase.co';let calls=0;global.fetch=async()=>{calls++;return response(401,{});};assert.equal((await call({action:'ads_catalog'})).code,503);assert.equal(calls,0);setup();assert.equal((await call({action:'ads_catalog'},'')).code,401);assert.equal((await call({action:'ads_catalog'})).code,401);});
test('admin denial is retained; no privileged RPC for review',async()=>{setup();const urls=[];global.fetch=async(url,options)=>{urls.push(url);if(url.endsWith('/auth/v1/user'))return response(200,{id:'user-admin-test'});assert.equal(options.headers.Authorization,'Bearer dummy');assert.equal(options.headers.apikey,'sb_publishable_fake');return response(403,{});};const r=await call({action:'ads_review',payload:{id:'campaign',status:'approved'}});assert.equal(r.code,403);assert.equal(urls.length,2);});
test('Stripe rejects live keys; test checkout uses authoritative frozen amount and trusted return host',async()=>{setup();let stripe=0;global.fetch=async(url,options)=>{if(url.endsWith('/auth/v1/user'))return response(200,{id:'user-checkout-test'});if(url.includes('/rest/v1/'))return response(200,{id:'campaign-1',price_cents:9900});stripe++;assert.equal(new URLSearchParams(options.body).get('line_items[0][price_data][unit_amount]'),'9900');assert.equal(new URLSearchParams(options.body).get('success_url'),'https://myevent-test-example.vercel.app/?ad_payment=returned');assert.equal(options.headers['Idempotency-Key'],'ads-test-campaign-1-9900');return response(200,{id:'cs_test_fake',url:'https://checkout.stripe.com/c/test'});};process.env.STRIPE_SECRET_KEY='sk_live_fake';assert.equal((await call({action:'ads_checkout',payload:{id:'campaign-1',amount:1}})).code,503);assert.equal(stripe,0);setup();const r=await call({action:'ads_checkout',payload:{id:'campaign-1',amount:1}});assert.equal(r.code,200);assert.equal(r.body.test,true);assert.equal(stripe,1);});
test('metrics require opt-in and matching short-lived receipt; replay cannot increment',async()=>{setup();let uid='viewer-one',counts=0;global.fetch=async(url,options)=>{if(url.endsWith('/auth/v1/user'))return response(200,{id:uid});if(url.endsWith('/myevent_ads_count')){counts++;assert.equal(options.headers.apikey,'sb_secret_fake');return response(200,true);}return response(200,[{id:'campaign-metric',title:'TEST'}]);};const f=await call({action:'ads_feed'}),token=f.body[0].metric_token;assert(token);assert.equal((await call({action:'ads_metric',payload:{token,kind:'impression',consent:false}})).body.counted,false);assert.equal(counts,0);uid='viewer-two';assert.equal((await call({action:'ads_metric',payload:{token,kind:'impression',consent:true}})).body.counted,false);uid='viewer-one';assert.equal((await call({action:'ads_metric',payload:{token,kind:'impression',consent:true}})).body.counted,true);assert.equal((await call({action:'ads_metric',payload:{token,kind:'impression',consent:true}})).body.counted,false);assert.equal(counts,1);assert.equal((await call({action:'ads_metric',payload:{token,kind:'click',consent:true}})).body.counted,true);assert.equal(counts,2);});
test('signed-event fulfillment adapter denies live/unpaid events and propagates real amount',async()=>{setup();let calls=0;global.fetch=async(url,o)=>{calls++;assert(url.endsWith('/myevent_ads_paid'));assert.deepEqual(JSON.parse(o.body),{p_id:'campaign-test',p_session:'cs_test_mock',p_amount:9900,p_currency:'eur'});return response(200,true);};const e={livemode:false,data:{object:{livemode:false,payment_status:'paid',metadata:{campaign_id:'campaign-test'},id:'cs_test_mock',amount_total:9900,currency:'eur'}}};await assert.rejects(()=>paid({...e,livemode:true}));await assert.rejects(()=>paid({...e,data:{object:{...e.data.object,payment_status:'unpaid'}}}));assert.equal(calls,0);assert.equal(await paid(e),true);assert.equal(calls,1);});
test('rate limiting caps authenticated requests without database event profiles',async()=>{setup();global.fetch=async url=>response(200,url.endsWith('/auth/v1/user')?{id:'rate-limit-user'}:{plans:[]});for(let i=0;i<40;i++)assert.equal((await call({action:'ads_catalog'})).code,200);assert.equal((await call({action:'ads_catalog'})).code,429);});
test.after(()=>{global.fetch=original;});
