const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const fs=require('fs'),path=require('path'),assert=require('node:assert/strict');
(async()=>{
const browser=await chromium.launch({headless:true,channel:'msedge'});const page=await browser.newPage({viewport:{width:390,height:844}});page.setDefaultTimeout(10000);
const root=path.resolve(__dirname,'..'),errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.route('**/*',async route=>{
 const u=new URL(route.request().url());if(u.hostname!=='myevent.test')return route.abort();
 const file=path.join(root,u.pathname==='/'?'index.html':decodeURIComponent(u.pathname));
 if(!file.startsWith(root)||!fs.existsSync(file))return route.fulfill({status:404,body:''});
 let body=fs.readFileSync(file);if(file.endsWith('index.html'))body=body.toString().replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi,'');
 return route.fulfill({body,contentType:file.endsWith('.html')?'text/html':file.endsWith('.css')?'text/css':/\.m?js$/.test(file)?'text/javascript':'application/octet-stream'});
});
await page.goto('http://myevent.test/');
await page.evaluate(()=>{let el=document.getElementById('socialBottomNav');while(el){el.style.setProperty('display','block','important');el=el.parentElement;}window.myeventCameraContext=()=>({sb:{auth:{getSession:async()=>({data:{session:{access_token:'fake'}}})}}});});
await page.addScriptTag({url:'/js/camera-capture2-final.js'});await page.addScriptTag({url:'/js/home-social-runtime.js'});
await page.locator('#socialBottomCreate').click();await page.locator('#cameraAiSide').click();await page.locator('[data-ai-generate]').waitFor();assert(await page.locator('[data-ai-generate]').isDisabled());
const images=await page.evaluate(()=>{const c=document.createElement('canvas');c.width=360;c.height=640;const x=c.getContext('2d');x.fillStyle='red';x.fillRect(0,0,360,640);const original=c.toDataURL('image/jpeg');x.fillStyle='blue';x.fillRect(0,0,360,640);return {original,result:c.toDataURL('image/webp')};});
await page.locator('#cameraFileInput').setInputFiles({name:'photo.jpg',mimeType:'image/jpeg',buffer:Buffer.from(images.original.split(',')[1],'base64')});
await page.waitForFunction(()=>document.getElementById('myeventCameraModal').dataset.cameraState==='preview');
await page.locator('[data-ai-generate]').waitFor();
await page.evaluate(({result})=>{window.aiRequests=[];window.aiMode='success';window.fetch=async(url,options)=>{if(url!=='/api/camera-ai')throw Error('Unexpected API');window.aiRequests.push(JSON.parse(options.body));if(window.aiMode==='pending')return new Promise((resolve,reject)=>{window.finishAI=()=>resolve({ok:true,json:async()=>({image:result})});options.signal.addEventListener('abort',()=>reject(new DOMException('Aborted','AbortError')));});return {ok:window.aiMode==='success',json:async()=>window.aiMode==='success'?{image:result}:{error:'Service indisponible'}};};},images);
await page.locator('[data-ai-generate]').click();await page.waitForFunction(()=>document.getElementById('myeventCameraModal').cameraHasAIPhoto());await page.waitForFunction(()=>document.getElementById('myeventCameraModal').dataset.cameraState==='preview');
const blue=await page.evaluate(()=>{const c=document.createElement('canvas');c.width=c.height=1;c.getContext('2d').drawImage(document.getElementById('myeventCapturedImage'),0,0,1,1);return [...c.getContext('2d').getImageData(0,0,1,1).data];});assert(blue[2]>200&&blue[0]<40);
assert.match(await page.locator('[role="status"]').filter({hasText:'filtre IA'}).textContent(),/appliqué/);
await page.locator('[data-ai-original]').click();await page.waitForFunction(()=>document.getElementById('myeventCameraModal').dataset.cameraState==='preview');assert(!(await page.evaluate(()=>document.getElementById('myeventCameraModal').cameraHasAIPhoto())));
const red=await page.evaluate(()=>{const c=document.createElement('canvas');c.width=c.height=1;c.getContext('2d').drawImage(document.getElementById('myeventCapturedImage'),0,0,1,1);return [...c.getContext('2d').getImageData(0,0,1,1).data];});assert(red[0]>200&&red[2]<40);
await page.getByRole('button',{name:'Animaux',exact:true}).click();await page.locator('[data-ai-lens="cat"]').click();await page.locator('[data-ai-generate]').click();await page.waitForFunction(()=>document.getElementById('myeventCameraModal').cameraHasAIPhoto());
assert.equal(await page.evaluate(()=>aiRequests.at(-1).lens),'cat');assert.equal(await page.evaluate(()=>aiRequests[0].imageData===aiRequests[1].imageData),true);
await page.waitForFunction(()=>document.getElementById('myeventCameraModal').dataset.cameraState==='preview');await page.evaluate(()=>window.aiMode='error');await page.locator('[data-ai-generate]').click();await page.getByText('Service indisponible',{exact:true}).waitFor();assert(await page.evaluate(()=>document.getElementById('myeventCameraModal').cameraHasAIPhoto()));
await page.evaluate(()=>window.aiMode='pending');await page.locator('[data-ai-generate]').click();await page.locator('[data-ai-cancel]').click();assert(await page.locator('[data-ai-generate]').isEnabled());assert(await page.evaluate(()=>document.getElementById('myeventCameraModal').cameraHasAIPhoto()));
await page.locator('[data-ai-generate]').click();await page.locator('#cameraCloseBtn').click();await page.evaluate(()=>window.finishAI?.());assert(!(await page.evaluate(()=>document.getElementById('myeventCameraModal').cameraHasAIPhoto())));
assert.deepEqual(errors,[]);console.log('PASS: real camera import, 12-style UI, preview gating, generation, source preserved, original restore, selected animal, error preserves photo, cancel, close ignores late response; no JS errors.');await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
