// Full-image rendering for stored and newly published camera JPEGs; no remote writes.
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright'),fs=require('fs'),path=require('path'),assert=require('assert/strict');
(async()=>{const browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_PATH,args:['--no-sandbox']});try{const page=await browser.newPage({viewport:{width:390,height:844}}),root=path.resolve(__dirname,'..'),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.route('**/*',r=>{const u=new URL(r.request().url());if(['blob:','data:'].includes(u.protocol))return r.continue();if(u.hostname!=='myevent.test')return r.abort();const file=path.resolve(root,u.pathname.slice(1)||'index.html');if(!file.startsWith(root+path.sep)||!fs.existsSync(file))return r.fulfill({status:404,body:''});let body=fs.readFileSync(file);if(file.endsWith('.html'))body=body.toString().replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi,'');return r.fulfill({body,contentType:file.endsWith('.html')?'text/html':file.endsWith('.css')?'text/css':'text/javascript'});});await page.goto('http://myevent.test/');
const photos=await page.evaluate(()=>{let el=document.getElementById('socialBottomNav');while(el){el.style.setProperty('display','block','important');el=el.parentElement;}const make=(w,h)=>{const c=document.createElement('canvas');c.width=w;c.height=h;const ctx=c.getContext('2d');ctx.fillStyle='#176b83';ctx.fillRect(0,0,w,h);ctx.fillStyle='#ffd166';ctx.fillRect(0,0,w,80);ctx.fillStyle='#ef476f';ctx.fillRect(0,h-80,w,80);ctx.fillStyle='#111';ctx.font='bold 30px sans-serif';ctx.fillText('HAUT · TEST',20,50);ctx.fillText('BAS · TEST',20,h-20);return c.toDataURL('image/jpeg',.9);};const vertical=make(360,640),horizontal=make(640,360);window.myeventLoadCameraPosts=async()=>window.savedFeedImage?[{id:'new-vertical',image:window.savedFeedImage}]:[{id:'old-vertical',image:vertical},{id:'old-horizontal',image:horizontal}];window.myeventPublishCameraPost=async image=>{window.savedFeedImage=image;return{id:'new-vertical'};};window.alert=()=>{};return{vertical,horizontal};});
for(const script of ['camera-annotations.js','camera-capture2-final.js','home-social-runtime.js'])await page.addScriptTag({url:'/js/'+script});await page.locator('[data-camera-post-id="old-vertical"] img').waitFor();
await page.locator('#socialBottomCreate').evaluate(e=>e.click());await page.locator('#cameraFileInput').setInputFiles({name:'vertical.jpg',mimeType:'image/jpeg',buffer:Buffer.from(photos.vertical.split(',')[1],'base64')});await page.waitForFunction(()=>document.getElementById('myeventCameraModal').dataset.cameraState==='preview');await page.locator('#cameraTextSide').click();await page.getByLabel('Texte sur la photo',{exact:true}).fill('SIGNATURE CONSERVÉE');await page.getByRole('button',{name:'Ajouter le texte',exact:true}).click();await page.waitForFunction(()=>document.getElementById('myeventCameraModal').dataset.cameraState==='preview');await page.locator('#cameraPanelClose').click();await page.getByRole('button',{name:'Terminé',exact:true}).click();const expected=await page.evaluate(async()=>{const f=await document.getElementById('myeventCameraModal').cameraGetMediaFile();return [...new Uint8Array(await f.arrayBuffer())];});await page.locator('#cameraPublishBtn').click();await page.locator('[data-camera-post-id="new-vertical"] img').waitFor();
assert.equal(await page.locator('[data-camera-post-id="old-vertical"] img').getAttribute('src'),photos.vertical);const published=await page.evaluate(()=>window.savedFeedImage);assert(Buffer.from(expected).equals(Buffer.from(published.split(',')[1],'base64')),'new post uses the exact decorated JPEG');
for(const [width,height] of [[320,844],[375,844],[390,844],[430,844],[1440,900],[844,390]]){
 await page.setViewportSize({width,height});
 const images=page.locator('[data-camera-post-id] img[alt="Photo MyEvent"]');assert.equal(await images.count(),3);
 for(let i=0;i<3;i++){
  const img=images.nth(i);await img.evaluate(e=>e.decode());const card=await img.evaluate(e=>({height:e.getBoundingClientRect().height,fit:getComputedStyle(e).objectFit,src:e.src}));assert.equal(card.height,250);assert.equal(card.fit,'cover');
  const button=img.locator('..');await button.scrollIntoViewIfNeeded();const position=await page.evaluate(()=>window.scrollY);await button.click();
  const dialog=page.locator('.socialFeedPhotoViewer');await dialog.waitFor({state:'visible'});const whole=dialog.locator('img');await whole.evaluate(e=>e.decode());
  const view=await whole.evaluate(e=>{const r=e.getBoundingClientRect();return {src:e.src,ratio:r.width/r.height,natural:e.naturalWidth/e.naturalHeight,width:r.width,height:r.height,fit:getComputedStyle(e).objectFit};});assert.equal(view.src,card.src);assert(Math.abs(view.ratio-view.natural)<.001);assert(view.width<=width&&view.height<=height);assert.equal(view.fit,'contain');
  if(i===0)await page.getByRole('button',{name:'Fermer la photo',exact:true}).click();else if(i===1)await page.keyboard.press('Escape');else await dialog.click({position:{x:5,y:height-5}});
  await dialog.waitFor({state:'hidden'});await page.waitForTimeout(40);assert(Math.abs(await page.evaluate(()=>window.scrollY)-position)<1,'scroll restored');assert(await button.evaluate(e=>document.activeElement===e),'focus restored');
 }
}
await page.setViewportSize({width:390,height:844});await page.locator('[data-camera-post-id="new-vertical"]').screenshot?.({path:path.join(root,'work/feed-compact-viewer.png')});assert.deepEqual(errors,[]);console.log('PASS compact feed + viewer: 250px cover, intact decorated source, full proportions, close/Escape/backdrop, scroll/focus restoration at mobile/desktop/landscape; zero JS errors');}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1);});
