// Local-only browser regression: real DOM/canvas/MediaRecorder; supplier/storage calls mocked.
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
(async()=>{
 const browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_PATH,args:['--no-sandbox','--disable-dev-shm-usage','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});
 const page=await browser.newPage({viewport:{width:390,height:844}});page.setDefaultTimeout(10000);
 const root=path.resolve(__dirname,'..'),errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.route('**/*',route=>{const u=new URL(route.request().url());if(u.hostname!=='myevent.test')return route.abort();const file=path.resolve(root,u.pathname.slice(1)||'index.html');if(!file.startsWith(root+path.sep)||!fs.existsSync(file))return route.fulfill({status:404,body:''});let body=fs.readFileSync(file);if(file.endsWith('index.html'))body=body.toString().replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi,'');return route.fulfill({body,contentType:file.endsWith('.html')?'text/html':file.endsWith('.css')?'text/css':/\.m?js$/.test(file)?'text/javascript':'application/octet-stream'});});
 await page.goto('http://myevent.test/');
 await page.evaluate(()=>{
  let el=document.getElementById('socialBottomNav');while(el){el.style.setProperty('display','block','important');el=el.parentElement;}
  window.calls=[];window.streams=[];window.mediaReady=0;
  navigator.mediaDevices={getUserMedia:async options=>{calls.push(options);const c=document.createElement('canvas');c.width=360;c.height=640;const ctx=c.getContext('2d');ctx.fillStyle='#d62424';ctx.fillRect(0,0,c.width,c.height);ctx.fillStyle='#401818';ctx.fillRect(0,0,80,80);const stream=c.captureStream(10);let interval=setInterval(()=>ctx.fillRect(0,0,2,2),50);window.streams.push(stream);stream.getTracks()[0].addEventListener('ended',()=>clearInterval(interval));if(options.audio){const audio=new AudioContext(),dest=audio.createMediaStreamDestination(),osc=audio.createOscillator();osc.connect(dest);osc.start();dest.stream.getAudioTracks().forEach(t=>stream.addTrack(t));window.audioTest=audio;}return stream;}};
 });
 for(const script of ['camera-annotations.js','camera-capture2-final.js','home-social-runtime.js','social-friends-stories.js'])await page.addScriptTag({url:'/js/'+script});
 await page.locator('#socialBottomCreate').evaluate(e=>e.click());await page.waitForFunction(()=>document.getElementById('myeventCameraVideo').readyState>=2);
 await page.locator('#cameraFlipBtn').click();await page.waitForFunction(()=>calls.at(-1).video.facingMode==='user'&&document.getElementById('myeventCameraVideo').readyState>=2);await page.locator('#cameraFlipBtn').click();await page.waitForFunction(()=>calls.at(-1).video.facingMode==='environment'&&document.getElementById('myeventCameraVideo').readyState>=2);
 await page.locator('#cameraSettingsBtn').click();await page.getByRole('button',{name:'Ratio',exact:true}).click();await page.getByRole('button',{name:'1:1',exact:true}).click();
 await page.locator('#cameraSettingsBtn').click();await page.getByRole('button',{name:'Minuteur',exact:true}).click();await page.getByRole('button',{name:'3 s',exact:true}).click();await page.locator('#cameraShutterBtn').click();assert.equal(await page.locator('#cameraCountdown').textContent(),'3');await page.waitForFunction(()=>document.getElementById('myeventCameraModal').dataset.cameraState==='preview');
 const exported=()=>page.evaluate(async()=>{const f=await document.getElementById('myeventCameraModal').cameraGetMediaFile();return f?Array.from(new Uint8Array(await f.arrayBuffer())).join(','):null;});
 const initial=await exported();
 const size=await page.locator('#myeventCapturedImage').evaluate(e=>[e.naturalWidth,e.naturalHeight]);assert.equal(size[0],size[1]);
 await page.locator('#cameraStickerSide').click();await page.getByLabel('Texte sur la photo').fill('MyEvent');await page.getByRole('button',{name:'Ajouter le texte',exact:true}).click();await page.waitForFunction(()=>document.getElementById('myeventCameraModal').dataset.cameraState==='preview'&&document.querySelector('.cameraDecorationLayer').hidden===false);
 const decorated=await exported();assert.notEqual(decorated,initial);
 await page.getByRole('button',{name:'Ajouter le sticker 🎉',exact:true}).click();await page.waitForFunction(()=>document.getElementById('myeventCameraModal').dataset.cameraState==='preview'&&document.querySelector('.cameraDecorationLayer').hidden===false);
 await page.locator('#cameraPanelClose').click();await page.locator('#cameraFilterSide').click();assert.equal(await page.locator('.cameraFilterChip img.thumb').count(),20);await page.locator('[data-filter="nb"]').click();await page.waitForFunction(()=>document.getElementById('myeventCameraModal').dataset.cameraState==='preview');
 const gray=await page.evaluate(()=>{const c=document.createElement('canvas');c.width=c.height=1;c.getContext('2d').drawImage(document.getElementById('myeventCapturedImage'),0,0,1,1);return [...c.getContext('2d').getImageData(0,0,1,1).data];});assert(Math.abs(gray[0]-gray[1])<3&&Math.abs(gray[1]-gray[2])<3);
 await page.locator('#cameraPanelClose').click();
 for(const width of [320,375,390,430]){await page.setViewportSize({width,height:844});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));const buttons=await page.locator('#cameraCapturedActions button').evaluateAll(els=>els.filter(e=>!e.hidden).map(e=>{const r=e.getBoundingClientRect();return {x:r.x,y:r.y,right:r.right,bottom:r.bottom};}));assert(buttons.every(r=>r.x>=0&&r.right<=width&&r.y>=0&&r.bottom<=844));}
 await page.setViewportSize({width:390,height:844});await page.screenshot({path:path.join(root,'work/camera-v2-photo.png')});
 await page.locator('#cameraStoryBtn').click();await page.locator('#storyMediaPreview img').waitFor();assert(await page.locator('#storyPublish').isVisible());assert(await page.locator('#myeventCameraModal').getAttribute('aria-hidden')==='true');
 // Retain explicit destination choice and RLS-backed photo service.
 await page.locator('#storyCloseSheet').click();await page.locator('#socialBottomCreate').evaluate(e=>e.click());await page.waitForFunction(()=>document.getElementById('myeventCameraVideo').readyState>=2);await page.locator('#cameraShutterBtn').click();await page.waitForFunction(()=>document.getElementById('myeventCameraModal').dataset.cameraState==='preview');
 await page.evaluate(()=>{const card=document.createElement('div');card.className='eventCard';card.dataset.eventId='test-event';card.innerHTML='<div class="eventCardTopInfo"><b>Test caméra</b></div>';document.getElementById('eventList').append(card);window.eventSaves=[];window.myeventAttachCameraPhoto=async(id,photo)=>eventSaves.push({id,photo});window.alert=()=>{};});
 await page.locator('#cameraAttachEventBtn').click();assert(await page.getByRole('button',{name:'Ajouter à cet événement',exact:true}).isDisabled());await page.getByLabel('Événement',{exact:true}).selectOption('test-event');assert.equal(await page.evaluate(()=>eventSaves.length),0);await page.getByRole('button',{name:'Ajouter à cet événement',exact:true}).click();await page.waitForFunction(()=>eventSaves.length===1);assert.equal(await page.evaluate(()=>eventSaves[0].id),'test-event');
 await page.locator('#socialBottomCreate').evaluate(e=>e.click());await page.locator('#cameraVideoBtn').click();await page.waitForFunction(()=>document.getElementById('myeventCameraVideo').srcObject?.getAudioTracks().length===1&&document.getElementById('myeventCameraVideo').readyState>=2);
 await page.locator('#cameraShutterBtn').click();await page.locator('#cameraShutterBtn.recording').waitFor();await page.waitForTimeout(1300);await page.locator('#cameraShutterBtn').click();await page.waitForFunction(()=>document.getElementById('myeventCameraModal').dataset.mediaKind==='video');
 assert(await page.locator('#myeventCapturedVideo').isVisible());assert(!(await page.locator('#cameraAttachEventBtn').isVisible()));assert(!(await page.locator('#cameraPublishBtn').isVisible()));
 await page.evaluate(async()=>window.recordedTestFile=await document.getElementById('myeventCameraModal').cameraGetMediaFile());
 await page.screenshot({path:path.join(root,'work/camera-v2-video.png')});await page.locator('#cameraStoryBtn').click();await page.locator('#storyMediaPreview video').waitFor();const file=await page.evaluate(()=>document.getElementById('storyMediaPreview').querySelector('video').src);assert(file.startsWith('blob:'));
 await page.locator('#storyCloseSheet').click();await page.locator('#socialBottomCreate').evaluate(e=>e.click());const clipData=await page.evaluate(async()=>({name:recordedTestFile.name,type:recordedTestFile.type,bytes:[...new Uint8Array(await recordedTestFile.arrayBuffer())]}));await page.locator('#cameraFileInput').setInputFiles({name:clipData.name,mimeType:clipData.type,buffer:Buffer.from(clipData.bytes)});await page.waitForFunction(()=>document.getElementById('myeventCameraModal').dataset.mediaKind==='video');assert(await page.locator('#myeventCapturedVideo').isVisible());await page.locator('#cameraCloseBtn').click();
 assert(await page.evaluate(()=>streams.every(s=>s.getTracks().every(t=>t.readyState==='ended'))));assert.deepEqual(errors,[]);console.log('PASS: real canvas capture, square crop, photo filter pixels, text/sticker JPEG, twenty real thumbnails, timer, front/rear switch, 320/375/390/430 layout, Story confirmation, explicit event save, real MediaRecorder clip/preview/Story/video import, streams released, zero JS errors.');await browser.close();
})().catch(e=>{console.error(e);process.exit(1);});
