// Local rendering and real MediaPipe/WebGL; never writes to a remote account.
const {chromium,webkit}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
(async()=>{
 const engine=process.env.TEST_BROWSER==='webkit'?webkit:chromium;
 const browser=await engine.launch({headless:true,...(engine===chromium?{executablePath:process.env.CHROMIUM_PATH,args:['--no-sandbox','--disable-dev-shm-usage','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']}: {})});
 const page=await browser.newPage({viewport:{width:390,height:744},hasTouch:true,isMobile:true});page.setDefaultTimeout(20000);
 const root=path.resolve(__dirname,'..'),errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.route('**/*',route=>{const u=new URL(route.request().url());if(['blob:','data:'].includes(u.protocol))return route.continue();if(u.hostname!=='myevent.test')return route.abort();const file=path.resolve(root,u.pathname.slice(1)||'index.html');if(!file.startsWith(root+path.sep)||!fs.existsSync(file))return route.fulfill({status:404,body:''});let body=fs.readFileSync(file);if(file.endsWith('index.html'))body=body.toString().replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi,'');return route.fulfill({body,contentType:file.endsWith('.html')?'text/html':file.endsWith('.css')?'text/css':/\.m?js$/.test(file)?'text/javascript':file.endsWith('.wasm')?'application/wasm':'application/octet-stream'});});
 await page.goto('http://myevent.test/');
 await page.evaluate(()=>{let el=document.getElementById('socialBottomNav');while(el){el.style.setProperty('display','block','important');el=el.parentElement;}const banner=document.createElement('div');banner.id='myeventEnvironmentBanner';banner.style.cssText='position:fixed;inset:0 0 auto;height:52px;z-index:2147483646;background:#ffdb70;pointer-events:none';banner.textContent='MYEVENT TEST';document.body.append(banner);});
 for(const script of ['camera-annotations.js','camera-capture2-final.js','home-social-runtime.js','social-friends-stories.js'])await page.addScriptTag({url:'/js/'+script});
 await page.locator('#socialBottomCreate').evaluate(e=>e.click());
 const raw=await page.evaluate(()=>{const c=document.createElement('canvas');c.width=640;c.height=960;const ctx=c.getContext('2d');ctx.fillStyle='#407880';ctx.fillRect(0,0,640,960);return c.toDataURL();});
 await page.locator('#cameraFileInput').setInputFiles({name:'photo.png',mimeType:'image/png',buffer:Buffer.from(raw.split(',')[1],'base64')});
 const ready=()=>page.waitForFunction(()=>document.getElementById('myeventCameraModal').dataset.cameraState==='preview');await ready();
 await page.locator('#cameraSignatureSide').click();assert.equal(await page.locator('[data-signature]').count(),4);
 const signatures=[];
 for(const style of ['classic','heart','crown','handwritten']){await page.locator(`[data-signature="${style}"]`).click();await ready();const data=await page.evaluate(()=>{const m=document.getElementById('myeventCameraModal'),c=document.createElement('canvas');c.width=640;c.height=960;m.cameraRenderDecorations(c);return c.toDataURL();});signatures.push(data);assert.equal(await page.getByLabel('Élément à modifier').locator('option').count(),1,'signature choice replaces selected signature');}
 assert.equal(new Set(signatures).size,4,'all four signatures have distinct real pixels');
 const alpha=()=>page.evaluate(()=>{const c=document.createElement('canvas');c.width=640;c.height=960;document.getElementById('myeventCameraModal').cameraRenderDecorations(c);const d=c.getContext('2d').getImageData(0,0,640,960).data;let sum=0;for(let i=3;i<d.length;i+=4)sum+=d[i];return sum;});
 const full=await alpha();await page.getByLabel('Opacité de l’élément').fill('50');await ready();const half=await alpha();assert(half>full*.45&&half<full*.55,'signature opacity changes actual export pixels');
 await page.getByLabel('Couleur du texte').fill('#ff8800');await ready();await page.locator('#cameraPanelClose').click();await page.waitForTimeout(100);
 const shape=()=>page.evaluate(()=>{const c=document.createElement('canvas');c.width=640;c.height=960;document.getElementById('myeventCameraModal').cameraRenderDecorations(c);const d=c.getContext('2d').getImageData(0,0,640,960).data;let sum=0,sx=0,sy=0;for(let i=3;i<d.length;i+=4){sum+=d[i];sx+=(i-3)/4%640*d[i];sy+=Math.floor((i-3)/4/640)*d[i];}return {x:sx/sum,y:sy/sum,sum};});
 const before=await shape(),layer=page.locator('.cameraDecorationLayer'),r=await layer.boundingBox(),center={x:r.x+before.x/640*r.width,y:r.y+before.y/960*r.height};
 const points=[{x:center.x-10,y:center.y},{x:center.x+10,y:center.y}],moved=[{x:center.x+24,y:center.y-20},{x:center.x+24,y:center.y+20}];
 if(engine===chromium){const cdp=await page.context().newCDPSession(page);await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:points.map((p,i)=>({...p,id:i+1}))});await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:moved.map((p,i)=>({...p,id:i+1}))});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});}
 else{for(const [type,p] of [['pointerdown',points],['pointermove',moved],['pointerup',moved]])await layer.evaluate((el,{type,p})=>p.forEach((point,i)=>el.dispatchEvent(new PointerEvent(type,{pointerId:i+1,pointerType:'touch',clientX:point.x,clientY:point.y,bubbles:true}))),{type,p});}
 await ready();const after=await shape();assert(after.sum>before.sum*3,'pinch scales the actual signature ink');assert(after.x>before.x+15,'touch translation moves exported signature');
 const parity=await page.evaluate(async()=>{const m=document.getElementById('myeventCameraModal'),file=await m.cameraGetMediaFile(),img=new Image();img.src=URL.createObjectURL(file);await img.decode();const c=m.cameraRenderDecorations(m.cameraRenderPhoto(m.cameraGetPhotoSource())),ctx=c.getContext('2d'),a=ctx.getImageData(0,0,c.width,c.height).data;ctx.drawImage(img,0,0);const b=ctx.getImageData(0,0,c.width,c.height).data;let error=0;for(let i=0;i<a.length;i+=4)for(let j=0;j<3;j++)error+=Math.abs(a[i+j]-b[i+j]);URL.revokeObjectURL(img.src);return error/(c.width*c.height*3);});assert(parity<3,'transformed pen signature/color/opacity survives actual final JPEG');
 await page.screenshot({path:path.join(root,`work/camera-v22-signature-${process.env.TEST_BROWSER||'chromium'}.png`)});
 await page.locator('#cameraFilterSide').click();await page.getByRole('button',{name:'Noir et blanc',exact:true}).click();assert.equal(await page.locator('.cameraFilterChip:visible').count(),3);
 await page.getByRole('button',{name:'Tous',exact:true}).click();assert.equal(await page.locator('.cameraFilterChip img').count(),20);
 await page.evaluate(()=>document.getElementById('myeventCameraModal').cameraSetFilter('sepia'));await ready();await page.getByLabel('Intensité du filtre',{exact:true}).fill('0');await ready();
 const identity=await page.evaluate(()=>{const m=document.getElementById('myeventCameraModal'),s=m.cameraGetPhotoSource(),r=m.cameraRenderPhoto(s),a=s.getContext('2d').getImageData(0,0,640,960).data,b=r.getContext('2d').getImageData(0,0,640,960).data;return a.every((v,i)=>v===b[i]);});assert(identity,'zero filter intensity is pixel-exact original');
 await page.getByLabel('Intensité du filtre',{exact:true}).fill('100');await ready();await page.locator('#cameraPanelClose').click();
 await page.locator('#cameraAppearanceSide').click();await page.locator('[data-effect="big-eyes"]').waitFor();await page.locator('[data-effect="big-eyes"]').click();await page.waitForFunction(()=>document.querySelector('.cameraAppearanceStatus')?.textContent==='Aucun visage détecté : photo conservée sans Apparence.',{},{timeout:90000});await ready();assert.equal(await page.locator('[data-effect="big-head"]').count(),1);assert.equal(await page.locator('[data-effect="small-face"]').count(),1);
 await page.getByRole('button',{name:'Cartoon 3D · IA',exact:true}).click();await page.getByRole('button',{name:'Cartoon 3D IA · après photo',exact:true}).click();await page.locator('[data-ai-lens="toon"][aria-pressed="true"]').waitFor();assert.equal(await page.locator('[data-ai-generate]').textContent(),'Transformer ma photo');await page.locator('#cameraPanelClose').click();
 const overlays=await page.evaluate(async()=>{const {drawAppearance,effects}=await import('/js/camera-appearance-renderer.mjs');const c=document.createElement('canvas');c.width=400;c.height=600;const ctx=c.getContext('2d'),marks=Array.from({length:478},()=>({x:.5,y:.5}));marks[33]={x:.3,y:.4};marks[263]={x:.7,y:.4};marks[10]={x:.5,y:.3};marks[13]={x:.5,y:.6};const results=[];for(const category of ['glasses','accessories','makeup'])for(const [id] of effects[category]){ctx.clearRect(0,0,400,600);drawAppearance(ctx,marks,{[category]:id},400,600,0);const zero=ctx.getImageData(0,0,400,600).data.some((v,i)=>i%4===3&&v);drawAppearance(ctx,marks,{[category]:id},400,600,1);const full=ctx.getImageData(0,0,400,600).data.some((v,i)=>i%4===3&&v);results.push({id,zero,full});}return results;});for(const effect of overlays)assert(!effect.zero&&effect.full,`tracked overlay ${effect.id} has real controllable pixels`);
 // Deformation must move pixels, not just draw a sticker. The zero setting must be identity.
 const warp=await page.evaluate(async()=>{const {FaceWarpRenderer}=await import('/js/camera-face-warp.mjs'),{effects}=await import('/js/camera-appearance-renderer.mjs');const src=document.createElement('canvas');src.width=src.height=256;const ctx=src.getContext('2d');for(let y=0;y<256;y++)for(let x=0;x<256;x++){ctx.fillStyle=`rgb(${x},${y},${(x+y)%256})`;ctx.fillRect(x,y,1,1);}const points=Array.from({length:478},()=>({x:.5,y:.5}));points[468]={x:.35,y:.4};points[473]={x:.65,y:.4};points[13]={x:.5,y:.65};points[14]={x:.5,y:.71};points[61]={x:.4,y:.65};points[291]={x:.6,y:.65};const canvas=document.createElement('canvas'),r=new FaceWarpRenderer(canvas),read=()=>{const copy=document.createElement('canvas');copy.width=copy.height=256;copy.getContext('2d').drawImage(canvas,0,0);return copy.getContext('2d').getImageData(0,0,256,256).data;};const original=ctx.getImageData(0,0,256,256).data;const difference=data=>{let sum=0;for(let i=0;i<data.length;i++)sum+=Math.abs(data[i]-original[i]);return sum/data.length;};const result={};for(const [effect] of effects.fun){r.render(src,points,effect,256,256,0);result[effect]={zero:difference(read())};r.render(src,points,effect,256,256,.5);result[effect].half=difference(read());r.render(src,points,effect,256,256,1);result[effect].full=difference(read());}r.close();return result;});
 console.log('Real WebGL deformations:',warp);
 for(const [id,result] of Object.entries(warp)){assert(result.zero<.1,`${id} zero identity ${result.zero}`);assert(result.full>.01,`${id} must deform real pixels`);assert(result.full>result.half,`${id} actual adjustable intensity`);}
 if(process.env.FACE_PHOTO_PATH){
   await page.evaluate(()=>document.getElementById('myeventCameraModal').dispatchEvent(new Event('camera-closed')));await page.locator('#cameraFileInput').setInputFiles(process.env.FACE_PHOTO_PATH);await ready();await page.locator('#cameraAppearanceSide').click();await page.getByRole('button',{name:'Déformations',exact:true}).click();await page.locator('[data-effect="big-eyes"]').click();
   await page.waitForFunction(()=>document.querySelector('.cameraAppearanceStatus')?.textContent==='Effets locaux intégrés à la photo.',{},{timeout:90000});await ready();
   const inferred=await page.evaluate(async()=>{const {FaceEngine}=await import('/js/camera-face-engine.mjs');const m=document.getElementById('myeventCameraModal'),engine=new FaceEngine();try{return (await engine.detect(m.cameraGetPhotoSource(),'IMAGE'))?.length||0;}finally{engine.close();}});assert(inferred>=468,'real MediaPipe detects supplied portrait');console.log('Real portrait MediaPipe landmarks:',inferred);
   await page.locator('#cameraPanelClose').click();await page.screenshot({path:path.join(root,`work/camera-v22-real-face-${process.env.TEST_BROWSER||'chromium'}.png`)});
 }else console.log('Real portrait inference not run: FACE_PHOTO_PATH absent.');
 assert.deepEqual(errors,[]);await browser.close();console.log('PASS V2.2 signatures/replacement/opacity, filter categories/intensity, Cartoon 3D real IA handoff, actual WebGL pixel warping + intensity, zero JavaScript errors.');
})().catch(e=>{console.error(e);process.exit(1);});
