// Full-image rendering for stored and newly published camera JPEGs; no remote writes.
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright'),fs=require('fs'),path=require('path'),assert=require('assert/strict');
(async()=>{const browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_PATH,args:['--no-sandbox']});try{const page=await browser.newPage({viewport:{width:390,height:844}}),root=path.resolve(__dirname,'..'),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.route('**/*',r=>{const u=new URL(r.request().url());if(['blob:','data:'].includes(u.protocol))return r.continue();if(u.hostname!=='myevent.test')return r.abort();const file=path.resolve(root,u.pathname.slice(1)||'index.html');if(!file.startsWith(root+path.sep)||!fs.existsSync(file))return r.fulfill({status:404,body:''});let body=fs.readFileSync(file);if(file.endsWith('.html'))body=body.toString().replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi,'');return r.fulfill({body,contentType:file.endsWith('.html')?'text/html':file.endsWith('.css')?'text/css':'text/javascript'});});await page.goto('http://myevent.test/');
const photos=await page.evaluate(()=>{let el=document.getElementById('socialBottomNav');while(el){el.style.setProperty('display','block','important');el=el.parentElement;}const make=(w,h)=>{const c=document.createElement('canvas');c.width=w;c.height=h;const ctx=c.getContext('2d');ctx.fillStyle='#176b83';ctx.fillRect(0,0,w,h);ctx.fillStyle='#ffd166';ctx.fillRect(0,0,w,80);ctx.fillStyle='#ef476f';ctx.fillRect(0,h-80,w,80);ctx.fillStyle='#111';ctx.font='bold 30px sans-serif';ctx.fillText('HAUT · TEST',20,50);ctx.fillText('BAS · TEST',20,h-20);return c.toDataURL('image/jpeg',.9);};const vertical=make(360,640),horizontal=make(640,360);window.myeventLoadCameraPosts=async()=>window.savedFeedImage?[{id:'new-vertical',image:window.savedFeedImage}]:[{id:'old-vertical',image:vertical},{id:'old-horizontal',image:horizontal}];window.myeventPublishCameraPost=async image=>{window.savedFeedImage=image;return{id:'new-vertical'};};window.alert=()=>{};return{vertical,horizontal};});
for(const script of ['camera-annotations.js','camera-capture2-final.js','home-social-runtime.js'])await page.addScriptTag({url:'/js/'+script});await page.locator('[data-camera-post-id="old-vertical"] img').waitFor();
await page.locator('#socialBottomCreate').evaluate(e=>e.click());await page.locator('#cameraFileInput').setInputFiles({name:'vertical.jpg',mimeType:'image/jpeg',buffer:Buffer.from(photos.vertical.split(',')[1],'base64')});await page.waitForFunction(()=>document.getElementById('myeventCameraModal').dataset.cameraState==='preview');await page.locator('#cameraTextSide').click();await page.getByLabel('Texte sur la photo',{exact:true}).fill('SIGNATURE CONSERVÉE');await page.getByRole('button',{name:'Ajouter le texte',exact:true}).click();await page.waitForFunction(()=>document.getElementById('myeventCameraModal').dataset.cameraState==='preview');await page.locator('#cameraPanelClose').click();await page.getByRole('button',{name:'Terminé',exact:true}).click();const expected=await page.evaluate(async()=>{const f=await document.getElementById('myeventCameraModal').cameraGetMediaFile();return [...new Uint8Array(await f.arrayBuffer())];});await page.locator('#cameraPublishBtn').click();await page.locator('[data-camera-post-id="new-vertical"] img').waitFor();
assert.equal(await page.locator('[data-camera-post-id="old-vertical"] img').getAttribute('src'),photos.vertical);const published=await page.evaluate(()=>window.savedFeedImage);assert(Buffer.from(expected).equals(Buffer.from(published.split(',')[1],'base64')),'new post uses the exact decorated JPEG');
for(const width of [320,375,390,430]){await page.setViewportSize({width,height:844});const checks=await page.locator('[data-camera-post-id] img[alt="Photo MyEvent"]').evaluateAll(async images=>{await Promise.all(images.map(img=>img.decode()));return images.map(img=>{const r=img.getBoundingClientRect(),s=getComputedStyle(img);return{id:img.parentElement.dataset.cameraPostId,fit:s.objectFit,ratio:(r.width-parseFloat(s.borderLeftWidth)-parseFloat(s.borderRightWidth))/(r.height-parseFloat(s.borderTopWidth)-parseFloat(s.borderBottomWidth)),natural:img.naturalWidth/img.naturalHeight,max:s.maxHeight,width:r.width};});});assert.equal(checks.length,3);for(const c of checks){assert.equal(c.fit,'contain');assert.equal(c.max,'none');assert(Math.abs(c.ratio-c.natural)<.02,JSON.stringify(c));assert(c.width<=width);}}
await page.setViewportSize({width:390,height:844});await page.locator('[data-camera-post-id="new-vertical"]').screenshot?.({path:path.join(root,'work/feed-full-image.png')});assert.deepEqual(errors,[]);console.log('PASS full feed: existing vertical/horizontal and new decorated JPEG keep exact sources and natural proportions at 320/375/390/430; zero JS errors');}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1);});
