import {PGlite} from '@electric-sql/pglite';
import {readFile} from 'node:fs/promises';
import assert from 'node:assert/strict';
const db=new PGlite(),a='11111111-1111-4111-8111-111111111111',b='22222222-2222-4222-8222-222222222222',c='33333333-3333-4333-8333-333333333333',event='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa';
await db.exec(`create role authenticated;create role anon;create schema auth;create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;grant usage on schema auth to authenticated;create table auth.users(id uuid primary key);create table events(id uuid primary key,creator_id uuid);create table event_members(event_id uuid,user_id uuid,role text);`);
const old=await readFile(new URL('../supabase/migrations/202609270005_event_roles_visibility_feed.sql',import.meta.url),'utf8');await db.exec(old.slice(old.indexOf('create or replace function public.event_is_member('),old.indexOf('create or replace function public.event_is_visible(')));
await db.exec(`insert into auth.users values('${a}'),('${b}'),('${c}');insert into events values('${event}','${a}');insert into event_members values('${event}','${b}','member');`);
await db.exec(await readFile(new URL('../supabase/migrations/202610050001_personal_reservations.sql',import.meta.url),'utf8'));
async function as(uid,sql,args=[]){return db.transaction(async tx=>{await tx.exec('set local role authenticated');await tx.query("select set_config('request.jwt.claim.sub',$1,true)",[uid]);return tx.query(sql,args);});}
const details={original_url:'https://www.abritel.fr/location-vacances/test',reservation_status:'added',name:'Fictif',proof:{name:'fictif.pdf',type:'application/pdf',size:5,base64:'JVBERi0='}};
const id=(await as(a,'insert into personal_reservations(kind,details) values($1,$2) returning id',['accommodation',details])).rows[0].id;
assert.equal((await as(a,'select * from personal_reservations')).rows.length,1);
assert.equal((await as(b,'select * from personal_reservations')).rows.length,0);
await as(a,'update personal_reservations set event_id=$1 where id=$2',[event,id]);
const shared=(await as(b,'select * from personal_reservations')).rows[0];assert.equal(shared.id,id);assert.deepEqual(shared.details.proof,details.proof);
assert.equal((await as(c,'select * from personal_reservations')).rows.length,0);
assert.equal((await as(b,'update personal_reservations set event_id=null returning id')).rows.length,0);
assert.equal((await as(b,'delete from personal_reservations returning id')).rows.length,0);
await assert.rejects(as(a,'update personal_reservations set owner_id=$1 where id=$2',[b,id]),/Identité/);
await assert.rejects(as(c,'insert into personal_reservations(kind,details,event_id) values($1,$2,$3)',['transport',details,event]));
await db.exec(`delete from event_members where user_id='${b}'`);assert.equal((await as(b,'select * from personal_reservations')).rows.length,0);
await as(a,'update personal_reservations set event_id=null where id=$1',[id]);assert.equal((await as(b,'select * from personal_reservations')).rows.length,0);
await as(a,'update personal_reservations set event_id=$1 where id=$2',[event,id]);await db.query('delete from events where id=$1',[event]);
const retained=(await as(a,'select * from personal_reservations')).rows[0];assert.equal(retained.event_id,null);assert.equal(retained.id,id);assert.deepEqual(retained.details.proof,details.proof);
await assert.rejects(as(a,'update personal_reservations set details=$1',[{...details,reservation_status:'confirmed'}]),/Confirmation/);
await assert.rejects(as(a,'update personal_reservations set details=$1',[{...details,proof:{...details.proof,base64:'YWJjZGU='}}]),/Contenu/);
await assert.rejects(as(a,'update personal_reservations set details=$1',[{...details,proof:{type:'application/pdf'}}]),/Justificatif/);
await assert.rejects(db.transaction(async tx=>{await tx.exec('set local role anon');await tx.exec('select * from personal_reservations');}));
console.log('Explorer RLS : propriétaire, membre, extérieur, anonyme, retrait, rattachement unique, justificatif et suppression événement validés.');await db.close();
