import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {createRequire} from 'node:module';import {execFileSync} from 'node:child_process';
const require=createRequire(import.meta.url),{JSDOM}=require('jsdom'),api=require('../js/reservation-link-contract.js'),personal=require('../js/personal-reservations.js');
const read=p=>readFileSync(new URL('../'+p,import.meta.url),'utf8'),tick=()=>new Promise(r=>setTimeout(r,20));
test('home shortcut is in the upper carousel; navigation, partner identifiers and appearance preferences are preserved',()=>{
 const before=new JSDOM(execFileSync('git',['show','fd3ebbd36a937b5a3775e883857443ee3d065073:index.html'],{encoding:'utf8',maxBuffer:4000000})),after=new JSDOM(read('index.html')),a=after.window.document,b=before.window.document;
 assert.ok(a.querySelector('.explorerCard'));assert.equal(a.querySelector('.explorerCard').closest('#eventsCard'),null);assert.equal(a.querySelector('.explorerCard').getAttribute('href'),'explorer.html');
 assert.deepEqual([...a.querySelectorAll('[data-bottom-tab]')].map(e=>e.outerHTML),[...b.querySelectorAll('[data-bottom-tab]')].map(e=>e.outerHTML));
 for(const selector of ['.eg-widget','[data-omio-widget]','.tnSearchWidget'])assert.deepEqual([...a.querySelectorAll(selector)].map(e=>e.outerHTML),[...b.querySelectorAll(selector)].map(e=>e.outerHTML));
 assert.equal(a.querySelector('#myeventAppearanceCard').outerHTML,b.querySelector('#myeventAppearanceCard').outerHTML);assert.equal(a.querySelectorAll('#myeventAdminEntry').length,1);assert.equal(a.querySelector('#myeventAdminEntry').closest('#profileSettingsCard').id,'profileSettingsCard');
 before.window.close();after.window.close();
});
function fixture(authenticated=true){
 const dom=new JSDOM(read('explorer.html'),{url:'https://preview.test/explorer.html',runScripts:'outside-only'}),w=dom.window,rows=[],calls=[],owner={id:'owner'},callbacks=[];
 w.MyEventReservationLink=api;w.MyEventPersonalReservations=personal;w.myeventRuntime={ready:Promise.resolve({url:'https://test.supabase.co',publishableKey:'test',authStorageKey:'test'})};
 w.HTMLElement.prototype.scrollIntoView=function(){};w.HTMLDialogElement.prototype.showModal=function(){this.open=true;};w.HTMLDialogElement.prototype.close=function(){this.open=false;};
 let nextError=null;
 const client={auth:{getUser:async()=>({data:{user:authenticated?owner:null}}),onAuthStateChange:fn=>callbacks.push(fn)},from(table){const state={op:'read',filters:[],payload:null};const q={select(){return q;},eq(k,v){state.filters.push([k,v]);return q;},order(){return q;},single(){return q;},maybeSingle(){return q;},insert(v){state.op='insert';state.payload=v;return q;},update(v){state.op='update';state.payload=v;return q;},delete(){state.op='delete';return q;},then(resolve){calls.push({table,...state});if(nextError){const error=nextError;nextError=null;return Promise.resolve({error}).then(resolve);}if(table==='events')return Promise.resolve({data:[{id:'event',name:'Événement fictif',creator_id:'owner'}]}).then(resolve);let selected=rows.filter(r=>state.filters.every(([k,v])=>r[k]===v));if(state.op==='insert'){const r={id:'unique',...state.payload,created_at:'2026-10-05'};rows.push(r);return Promise.resolve({data:r}).then(resolve);}if(state.op==='update'){selected.forEach(r=>Object.assign(r,state.payload));return Promise.resolve({data:selected[0]}).then(resolve);}return Promise.resolve({data:selected}).then(resolve);}};return q;}};
 w.supabase={createClient:()=>client};w.eval('(async()=>{'+read('js/explorer.mjs')+'})()');return {w,rows,calls,callbacks,dom,setError:e=>nextError=e};
}
test('personal link form saves without an event; attachment updates the same row; logout clears private content',async()=>{
 const f=fixture();try{await tick();const d=f.w.document;d.getElementById('add').click();const form=d.getElementById('bookingForm'),el=form.elements;el.original_url.value='https://www.abritel.fr/location-vacances/test?chkin=2026-10-05&destination=Gap&adults=2';d.getElementById('extract').click();assert.equal(el.start.value,'2026-10-05');assert.equal(el.travelers.value,'2');assert.equal(el.lat.value,'');el.name.value='Logement fictif';
 assert.equal(el.kind.value,'accommodation');form.dispatchEvent(new f.w.Event('submit',{cancelable:true}));await tick();assert.equal(f.rows.length,0);el.consent.checked=true;form.dispatchEvent(new f.w.Event('submit',{cancelable:true}));await tick();assert.equal(f.rows.length,1);assert.equal(f.rows[0].event_id,null);assert.match(d.getElementById('bookings').textContent,/Logement fictif/);
 d.querySelector('#bookings select').value='event';[...d.querySelectorAll('#bookings button')].find(b=>b.textContent==='Partager avec cet événement').click();await tick();assert.equal(f.rows.length,1);assert.equal(f.rows[0].id,'unique');assert.equal(f.rows[0].event_id,'event');assert.equal(f.rows[0].details.original_url,el.original_url.value);
 f.callbacks[0]('SIGNED_OUT',null);await tick();assert.equal(d.getElementById('bookings').textContent,'');assert.equal(form.elements.name.value,'');
 }finally{f.dom.window.close();}
});
test('anonymous searches do not require an event; personal saving requires authentication',async()=>{const f=fixture(false);try{await tick();f.w.document.querySelector('[data-category=accommodation]').click();assert.equal(f.w.document.querySelector('iframe').getAttribute('src'),'explorer-partners.html?kind=accommodation');f.w.document.getElementById('add').click();assert.equal(f.w.document.getElementById('bookingDialog').open,false);assert.equal(f.rows.length,0);}finally{f.dom.window.close();}});
test('missing schema produces an explicit activation error rather than claiming persistence',async()=>{const client={from(){const q={select:()=>q,eq:()=>q,order:()=>Promise.resolve({error:{code:'PGRST205'}})};return q;}};await assert.rejects(personal.create(client,'owner').list(),/pas encore activées/);});
test('proof file MIME is insufficient without valid bytes',async()=>{await assert.rejects(personal.proof({name:'false.pdf',type:'application/pdf',size:5,arrayBuffer:async()=>new TextEncoder().encode('false').buffer}),/contenu/);});
test('generated partner pages retain canonical affiliate configuration and load the official SDK before DOMContentLoaded',()=>{
 execFileSync(process.execPath,['scripts/generate-explorer-partners.cjs']);const canonical=new JSDOM(read('index.html')).window.document;
 for(const kind of ['accommodation','transport','ticket']){const page=read('explorer-partners-'+kind+'.html'),dom=new JSDOM(page),doc=dom.window.document;
  for(const widget of doc.querySelectorAll('.eg-widget'))assert.equal(widget.outerHTML,canonical.getElementById(widget.id).outerHTML);
  if(kind!=='ticket'){const sdk=doc.querySelector('script.eg-widgets-script');assert.equal(sdk.getAttribute('src'),canonical.querySelector('script.eg-widgets-script').getAttribute('src'));assert.equal(sdk.hasAttribute('async'),false);assert.equal(sdk.hasAttribute('defer'),false);assert.equal(doc.querySelectorAll('script.eg-widgets-script').length,1);}
  if(kind==='transport')assert.equal(doc.querySelector('[data-omio-widget]').outerHTML,canonical.querySelector('[data-omio-widget]').outerHTML);
  if(kind==='ticket')assert.equal(doc.querySelector('.tnSearchWidget').outerHTML,canonical.querySelector('.tnSearchWidget').outerHTML);
  assert.equal(doc.querySelector('#m58AccommodationSearchCancel'),null);dom.window.close();
 }
});
test('a known travel provider corrects a previously selected restaurant category; unknown restaurant links keep the choice',async()=>{const f=fixture();try{await tick();const d=f.w.document;d.querySelector('[data-category=restaurant]').click();d.getElementById('add').click();const el=d.getElementById('bookingForm').elements;assert.equal(el.kind.value,'restaurant');el.original_url.value='https://www.abritel.fr/location-vacances/test';d.getElementById('extract').click();assert.equal(el.kind.value,'accommodation');el.kind.value='restaurant';el.original_url.value='https://restaurant.example.com/reservation';d.getElementById('extract').click();assert.equal(el.kind.value,'restaurant');}finally{f.dom.window.close();}});
test('nearby restaurant search expands an empty radius; approximate activities never create an exact marker',async()=>{
 const f=fixture(false),w=f.w,radii=[],markers=[];try{await tick();Object.defineProperty(w.navigator,'geolocation',{value:{getCurrentPosition:resolve=>resolve({coords:{latitude:44.5,longitude:6.1}})}});w.AbortSignal=AbortSignal;
 const group={addTo(){return group;},clearLayers(){markers.length=0;}};const map={setView(){return map;},invalidateSize(){}};w.L={map:()=>map,tileLayer:()=>({addTo(){}}),layerGroup:()=>group,marker:coords=>({addTo(){markers.push(coords);return this;},bindPopup(){return this;}})};
 w.fetch=async url=>{const u=new URL(url,w.location.href);radii.push(Number(u.searchParams.get('radius')));return {ok:true,json:async()=>({results:u.searchParams.get('mode')==='viator'?[{name:'Activité fictive',type:'viator_activity',lat:44.5,lon:6.1,locationApproximate:true,website:'https://www.viator.com/test'}]:radii.length===1?[]:[{name:'Restaurant fictif',type:'restaurant',lat:44.51,lon:6.1}]})};};
 w.document.querySelector('[data-category=restaurant]').click();w.document.getElementById('locate').click();await tick();assert.deepEqual(radii,[5,10]);assert.equal(markers.length,1);assert.match(w.document.getElementById('searchNotice').textContent,/recherche élargie/);assert.match(w.document.getElementById('places').textContent,/1.1 km à vol d’oiseau/);
 w.document.querySelector('[data-category=activity]').click();w.document.getElementById('locate').click();await tick();assert.equal(markers.length,0);assert.match(w.document.getElementById('places').textContent,/Localisation indicative/);assert.doesNotMatch(w.document.getElementById('places').textContent,/0.0 km/);
 }finally{f.dom.window.close();}
});
