import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import {readFile} from 'node:fs/promises';
const source=await readFile(new URL('../js/game-session.js',import.meta.url),'utf8');
function setup(rpc,prefix='game'){let removed=0;const intervals=new Set(),window={};const sb={rpc,channel:()=>({on(){return this},subscribe(cb){cb('SUBSCRIBED');return this}}),removeChannel(){removed++;}};vm.runInNewContext(source,{window,EventTarget,CustomEvent,document:{hidden:false},setInterval:fn=>{intervals.add(fn);return fn;},clearInterval:fn=>intervals.delete(fn)});return {session:new window.MyEventGameSession(()=>({sb,user:{id:'a'}}),prefix),intervals,removed:()=>removed};}
test('a failed initial snapshot never reports a joined room',async()=>{const {session,intervals}=setup(async()=>({error:Error('Accès refusé')}));await assert.rejects(session.connect('room'),/Accès refusé/);assert.equal(session.roomId,null);assert.equal(intervals.size,0);});
test('disconnect clears subscriptions and ignores a stale response',async()=>{let release;const {session,intervals,removed}=setup(async()=>({data:{room:{revision:1}}}));await session.connect('first');assert.equal(intervals.size,2);session.context().sb.rpc=()=>new Promise(resolve=>release=resolve);const pending=session.refresh();session.disconnect();release({data:{secret:{word:'stale'},room:{revision:2}}});await pending;assert.equal(session.state,null);assert.equal(intervals.size,0);assert.equal(removed(),1);});
test('server action failures are not reflected as local success',async()=>{const {session}=setup(async(name)=>name==='game_snapshot'?{data:{room:{revision:4}}}:{error:Error('Vote refusé')});await session.connect('room');await assert.rejects(session.act('vote',{target:'x'}),/Vote refusé/);assert.equal(session.state.room.revision,4);session.disconnect();});

test('a custom game namespace reuses the same transport',async()=>{const names=[];const {session}=setup(async(name)=>{names.push(name);if(name==='defis_create')return {data:'room'};if(name==='defis_snapshot')return {data:{room:{revision:1,game_key:'defis'}}};if(name==='defis_action')return {data:null};return {data:null};},'defis');await session.create({players:4,challenges:5});await session.act('ready',{ready:true});assert.ok(names.includes('defis_create'));assert.ok(names.includes('defis_snapshot'));assert.ok(names.includes('defis_action'));session.disconnect();});
test('leaving a custom game uses its own RPC and clears the session',async()=>{const names=[];const {session}=setup(async name=>{names.push(name);return name==='defis_snapshot'?{data:{room:{revision:1}}}:{data:null};},'defis');await session.connect('room');await session.leave();assert.ok(names.includes('defis_action'));assert.equal(names.includes('game_action'),false);assert.equal(session.roomId,null);});
