import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import {JSDOM} from 'jsdom';
test('HTTP 502 displays safe diagnostics and clears them before a later network failure',async()=>{
 const dom=new JSDOM('<div id="m58AccommodationSearchBox"><div id="partner">Affiliate widget</div></div>',{url:'https://preview.example',runScripts:'outside-only'}),w=dom.window;w.AbortSignal=globalThis.AbortSignal;
 w.fetch=async()=>({ok:false,json:async()=>({error:'Configuration Sabre CERT invalide.',code:'SABRE_CERT_BASE_INVALID',diagnostics:{stage:'configuration'}})});
 w.eval(fs.readFileSync('js/hotel-search.js','utf8'));w.document.dispatchEvent(new w.Event('DOMContentLoaded'));const form=w.document.querySelector('form');form.elements.destination.value='Paris';form.elements.checkIn.value='2026-11-10';form.elements.checkOut.value='2026-11-12';
 const submit=async()=>{form.dispatchEvent(new w.Event('submit',{cancelable:true}));await new Promise(r=>setTimeout(r,10));};await submit();
 assert.match(w.document.querySelector('[role=status]').textContent,/Configuration/);assert.doesNotMatch(w.document.querySelector('[role=status]').textContent,/0 hôtel/);assert.equal(w.document.querySelector('details').hidden,false);assert.match(w.document.querySelector('pre').textContent,/configuration/);assert.ok(w.document.querySelector('#partner'));
 w.fetch=async()=>{throw Error('Network failure');};await submit();assert.equal(w.document.querySelector('details').hidden,true);assert.equal(w.document.querySelector('pre').textContent,'');dom.window.close();
});
test('unavailable CERT search hides the hotel count while a successful empty search keeps it',async()=>{
 const dom=new JSDOM('<div id="m58AccommodationSearchBox"><div id="partner">Affiliate widget</div></div>',{url:'https://preview.example',runScripts:'outside-only'}),w=dom.window;
 w.AbortSignal=globalThis.AbortSignal;
 let state='unavailable';
 w.fetch=async()=>({ok:true,json:async()=>({status:state,results:[],supplierCount:0,warnings:state==='unavailable'?['WARN.0366']:[]})});
 w.eval(fs.readFileSync('js/hotel-search.js','utf8'));w.document.dispatchEvent(new w.Event('DOMContentLoaded'));
 const form=w.document.querySelector('form');form.elements.destination.value='Paris';form.elements.checkIn.value='2026-11-10';form.elements.checkOut.value='2026-11-12';
 const submit=async()=>{form.dispatchEvent(new w.Event('submit',{cancelable:true}));await new Promise(r=>setTimeout(r,10));return w.document.querySelector('[role=status]').textContent;};
 assert.match(await submit(),/Recherche indisponible/);assert.doesNotMatch(w.document.querySelector('[role=status]').textContent,/0 hôtel|Aucun hôtel/);assert.ok(w.document.querySelector('#partner'));
 state='empty';assert.match(await submit(),/0 hôtel\(s\)/);assert.match(w.document.querySelector('[role=status]').textContent,/Aucun hôtel retourné/);dom.window.close();
});
test('shared hotel UI renders actual fields safely, deduplicates pages and preserves partners on errors',async()=>{const dom=new JSDOM('<div id="m58AccommodationSearchBox"><div id="partner">Affiliate widget</div></div>',{url:'https://preview.example',runScripts:'outside-only'}),w=dom.window;w.AbortSignal=globalThis.AbortSignal;let calls=[];w.fetch=async(url,opts)=>{calls.push(JSON.parse(opts.body));return {ok:true,json:async()=>({results:[{id:'1',name:'<script>unsafe</script>',source:'sabre-cert',price:null,image:'javascript:alert(1)',equipment:[]}],nextOffset:calls.length===1?2:null,warnings:[]})};};w.eval(fs.readFileSync('js/place-card.js','utf8'));w.eval(fs.readFileSync('js/hotel-search.js','utf8'));w.document.dispatchEvent(new w.Event('DOMContentLoaded'));const form=w.document.querySelector('form');form.elements.destination.value='Paris';form.elements.checkIn.value='2026-11-10';form.elements.checkOut.value='2026-11-12';form.dispatchEvent(new w.Event('submit',{cancelable:true}));await new Promise(r=>setTimeout(r,10));assert.equal(w.document.querySelectorAll('article').length,1);assert.equal(w.document.querySelectorAll('article script, article img').length,0);assert.ok(w.document.querySelector('#partner'));w.document.querySelector('.hotelSearchMore').click();await new Promise(r=>setTimeout(r,10));assert.equal(calls[1].offset,2);assert.equal(w.document.querySelectorAll('article').length,1);assert.equal(w.document.querySelector('.hotelSearchMore').hidden,true);w.fetch=async()=>{throw Error('Network failure')};form.dispatchEvent(new w.Event('submit',{cancelable:true}));await new Promise(r=>setTimeout(r,10));assert.equal(w.document.querySelectorAll('article').length,0);assert.match(w.document.querySelector('[role=status]').textContent,/Network failure/);assert.ok(w.document.querySelector('#partner'));dom.window.close();});
