import test from 'node:test';import assert from 'node:assert/strict';import {createRequire} from 'node:module';
const require=createRequire(import.meta.url),{createSabreProvider,request,normalize}=require('../lib/sabre-provider');
const query={destination:'Paris',checkIn:'2026-11-10',checkOut:'2026-11-12',guests:2,rooms:1,type:'hotel',lat:48.8566,lon:2.3522};
const row={HotelInfo:{HotelCode:'123',HotelName:'HÃ´tel fixture',LocationInfo:{Latitude:'48.85',Longitude:'2.35',Address:{AddressLine1:'Adresse fixture',CityName:{CityName:'Paris'}}}},HotelRateInfo:{RateInfos:{ConvertedRateInfo:[{CurrencyCode:'EUR',AmountAfterTax:'250',TaxInclusive:true},{CurrencyCode:'EUR',AmountAfterTax:'200'},{CurrencyCode:'USD',AmountAfterTax:'1'}]}},HotelImageInfo:{ImageItem:{Image:{Url:'https://example.com/hotel.jpg'}}}};
test('Sabre request v5 uses actual dates, adults per room and explicit geographic criteria',()=>{const q=request(query,{lat:query.lat,lon:query.lon}).GetHotelAvailRQ.SearchCriteria;assert.deepEqual(q.RateInfoRef.StayDateTimeRange,{StartDate:'2026-11-10',EndDate:'2026-11-12'});assert.deepEqual(q.RateInfoRef.Rooms.Room,[{Index:1,Adults:2}]);assert.equal(q.GeoSearch.GeoRef.UOM,'KM');assert.throws(()=>request({...query,guests:3,rooms:2},query),/nombre/);});
test('normalization preserves currency, total stay basis, missing metadata; never invents booking',()=>{const r=normalize(row,query);assert.equal(r.price,200);assert.equal(r.currency,'EUR');assert.equal(r.priceBasis,'total-stay');assert.equal(r.bookingAvailable,false);assert.ok(r.distance>0);assert.equal(r.image,'https://example.com/hotel.jpg');const empty=normalize({HotelInfo:{HotelName:'Sans tarif'}},query);assert.equal(empty.price,null);assert.equal(empty.currency,'');assert.equal(empty.lat,null);assert.equal(empty.image,'');});
test('CERT search is server-only, allows Complete and rejects failed requests without upstream secrets',async()=>{
 const calls=[],provider=createSabreProvider({env:{SABRE_USERNAME:'fixture-user',SABRE_PASSWORD:'fixture-password'},fetcher:async(url,options)=>{calls.push({url,options});if(url.endsWith('/v2/auth/token'))return {ok:true,json:async()=>({access_token:'private-fixture',expires_in:3600})};return {ok:true,json:async()=>({GetHotelAvailRS:{ApplicationResults:{status:'Complete'},HotelAvailInfos:{HotelAvailInfo:[row]}}})};}});const result=await provider.search(query);assert.equal(result.status,'ok');assert.equal(calls[1].url,'https://api.cert.platform.sabre.com/v5/get/hotelavail');assert.equal(calls[1].options.headers.Authorization,'Bearer private-fixture');assert.ok(!JSON.stringify(result).includes('private-fixture'));assert.equal(result.bookingAvailable,false);
 for(const data of [{GetHotelAvailRS:{ApplicationResults:{status:'NotProcessed'}}},{}])await assert.rejects(createSabreProvider({env:{SABRE_USERNAME:'fixture-user2',SABRE_PASSWORD:'fixture-password2'},fetcher:async url=>({ok:true,json:async()=>url.endsWith('/v2/auth/token')?{access_token:'fixture'}:data})}).search(query),/recherche/);
});
test('missing config and production never call CERT; empty Complete is explicit',async()=>{
 for(const env of [{},{SABRE_USERNAME:'fixture-user2',SABRE_PASSWORD:'fixture-password2',VERCEL_ENV:'production'}]){const r=await createSabreProvider({env,fetcher:()=>{throw Error('must not fetch');}}).search(query);assert.equal(r.status,'unavailable');}
 const r=await createSabreProvider({env:{SABRE_USERNAME:'fixture-user2',SABRE_PASSWORD:'fixture-password2'},fetcher:async url=>({ok:true,json:async()=>url.endsWith('/v2/auth/token')?{access_token:'fixture'}:({GetHotelAvailRS:{ApplicationResults:{status:'Complete'},HotelAvailInfos:{HotelAvailInfo:[]}}})})}).search(query);assert.equal(r.status,'empty');
});

test('authentication error and redirect rejection never leak upstream body or credentials',async()=>{let called=0;await assert.rejects(createSabreProvider({env:{SABRE_USERNAME:'auth-error',SABRE_PASSWORD:'secret'},fetcher:async(url,opts)=>{called++;assert.equal(opts.redirect,'error');return {ok:false,status:401,json:()=>{throw Error('body must not be read')}};}}).search(query),/^Error: Authentification Sabre CERT refusée \(HTTP 401\)\.$/);assert.equal(called,1);});
test('pagination and deduplication preserve only actual hotel data',async()=>{const hotelRows=Array.from({length:40},()=>row);const r=await createSabreProvider({env:{SABRE_USERNAME:'pages',SABRE_PASSWORD:'fixture'},fetcher:async url=>({ok:true,json:async()=>url.endsWith('/v2/auth/token')?{access_token:'fixture',expires_in:100}:({GetHotelAvailRS:{ApplicationResults:{status:'Complete'},HotelAvailInfos:{OffSet:1,MaxSearchResults:80,HotelAvailInfo:hotelRows}}})})}).search(query);assert.equal(r.results.length,1);assert.equal(r.nextOffset,2);});
