// Only called by the existing payment function; no additional Vercel function.
const crypto=require('node:crypto');
const limits=new Map(),receipts=new Map();
function sweep(now){for(const [k,v] of limits)if(v.until<=now)limits.delete(k);for(const [k,v] of receipts)if(v.until<=now)receipts.delete(k);}
async function environment(){const {supabaseEnvironment}=await import('./supabase-environment.mjs');const c=supabaseEnvironment();if(!c.isTest||c.projectRef!=='ahyyknfjsielnqyoxqgh')throw Error('TEST_ONLY');return c;}
async function rpc(c,token,action,payload){const response=await fetch(c.url+'/rest/v1/rpc/myevent_ads',{method:'POST',headers:{apikey:c.publishableKey,Authorization:'Bearer '+token,'Content-Type':'application/json'},body:JSON.stringify({p_action:action,p_payload:payload}),signal:AbortSignal.timeout(8000)});if(!response.ok)throw Error('RPC_'+response.status);return response.json();}
async function service(c,name,args){const key=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!key)throw Error('SERVICE_NOT_CONFIGURED');const r=await fetch(c.url+'/rest/v1/rpc/'+name,{method:'POST',headers:{apikey:key,...(key.startsWith('eyJ')?{Authorization:'Bearer '+key}:{}),'Content-Type':'application/json'},body:JSON.stringify(args),signal:AbortSignal.timeout(8000)});if(!r.ok)throw Error('SERVICE_FAILED');return r.json();}
async function handler(req,res){res.setHeader('Cache-Control','no-store');try{
 if(req.method!=='POST')return res.status(405).json({error:'Méthode non autorisée.'});
 const c=await environment(),token=/^Bearer ([^\s]+)$/.exec(req.headers.authorization||'')?.[1];if(!token)return res.status(401).json({error:'Connexion requise.'});
 const auth=await fetch(c.url+'/auth/v1/user',{headers:{apikey:c.publishableKey,Authorization:'Bearer '+token},signal:AbortSignal.timeout(5000)});if(!auth.ok)return res.status(401).json({error:'Session invalide.'});const uid=(await auth.json()).id;if(!uid)return res.status(401).json({error:'Session invalide.'});
 const now=Date.now();sweep(now);let rate=limits.get(uid);if(!rate){if(limits.size>=2000)return res.status(503).json({error:'Réessayez plus tard.'});rate={count:0,until:now+60000};limits.set(uid,rate);}if(++rate.count>40)return res.status(429).json({error:'Trop d’appels. Réessayez dans une minute.'});
 const body=req.body||{};if(Buffer.byteLength(JSON.stringify(body))>5000)return res.status(413).json({error:'Campagne trop volumineuse.'});const action=body.action?.replace(/^ads_/,''),payload=body.payload||{};
 if(action==='feed'){const rows=await rpc(c,token,'feed',{});return res.status(200).json(rows.map(row=>{if(receipts.size>=4000)return row;const key=crypto.randomUUID();receipts.set(key,{id:row.id,uid,until:now+300000,impression:false,click:false});return {...row,metric_token:key};}));}
 if(action==='metric'){if(payload.consent!==true)return res.status(200).json({counted:false});const receipt=receipts.get(payload.token),kind=payload.kind;if(!receipt||receipt.uid!==uid||!['impression','click'].includes(kind)||receipt[kind])return res.status(200).json({counted:false});receipt[kind]=true;try{await rpc(c,token,'catalog',{});const counted=await service(c,'myevent_ads_count',{p_id:receipt.id,p_kind:kind});return res.status(200).json({counted});}catch(e){receipt[kind]=false;throw e;}}
 if(action==='checkout'){
  const key=process.env.STRIPE_SECRET_KEY;if(!/^sk_test_/.test(key||''))return res.status(503).json({error:'Stripe TEST non configuré. Paiement désactivé.'});
  const campaign=await rpc(c,token,'quote',{id:payload.id});const host=process.env.VERCEL_URL;if(!/^[a-z0-9.-]+\.vercel\.app$/.test(host||''))throw Error('PREVIEW_URL_REQUIRED');
  const params=new URLSearchParams({mode:'payment',success_url:'https://'+host+'/?ad_payment=returned',cancel_url:'https://'+host+'/?ad_payment=cancelled','line_items[0][quantity]':'1','line_items[0][price_data][currency]':'eur','line_items[0][price_data][unit_amount]':String(campaign.price_cents),'line_items[0][price_data][product_data][name]':'MyEvent · Campagne TEST','metadata[myevent_kind]':'ads_test','metadata[campaign_id]':campaign.id});
  const r=await fetch('https://api.stripe.com/v1/checkout/sessions',{method:'POST',headers:{Authorization:'Bearer '+key,'Content-Type':'application/x-www-form-urlencoded','Idempotency-Key':'ads-test-'+campaign.id+'-'+campaign.price_cents},body:params.toString(),signal:AbortSignal.timeout(10000)});const data=await r.json();if(!r.ok||!/^cs_test_/.test(data.id)||!/^https:\/\/checkout\.stripe\.com\//.test(data.url))throw Error('STRIPE_FAILED');return res.status(200).json({url:data.url,test:true});
 }
 if(!['catalog','mine','create','admin_list','review','plan','settings','external_revenue'].includes(action))return res.status(400).json({error:'Action invalide.'});
 return res.status(200).json(await rpc(c,token,action,payload));
 }catch(e){const denied=e.message==='TEST_ONLY'||e.message==='RPC_403';return res.status(denied?403:503).json({error:denied?'Accès refusé. Régie réservée à l’environnement TEST.':'Régie indisponible : vérifier la migration TEST et la configuration serveur.'});}}
async function paid(event){const c=await environment(),s=event.data.object;if(event.livemode!==false||s.livemode!==false||s.payment_status!=='paid'||!/^sk_test_/.test(process.env.STRIPE_SECRET_KEY||''))throw Error('INVALID_TEST_PAYMENT');return service(c,'myevent_ads_paid',{p_id:s.metadata.campaign_id,p_session:s.id,p_amount:s.amount_total,p_currency:s.currency});}
module.exports={handler,paid};
